dentsusoken/iPLAss

iplass-tools-batch/src/main/java/org/iplass/mtp/tools/ToolsBatchResourceBundleUtil.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/MtpCuiBase.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityJavaMappingClassCreator.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataImport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataNameListExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageImport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/partition/MySQLPartitionBatch.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/storagespace/ObjStoreDDLGenerateBatch.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/storagespace/StorageSpaceCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/storagespace/StorageSpaceMigration.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/tenant/TenantBatch.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/gui/MtpJDialogBase.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/gui/MtpJFrameBase.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/gui/partition/MySQLPartitionManagerApp.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/gui/partition/PartitionCreateDialog.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/gui/tenant/TenantCreateDialog.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/gui/tenant/TenantDeleteDialog.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/gui/tenant/TenantManagerApp.java
#20 対応。
・CuiBaseでlanguage制御
・Gui側も同様の方式で対応
・Commonのメッセージもフルパスで指定(grepしやすいように)
=> メッセージの取得処理を改善

iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/entityexplorer/datalist/EntityTreeGrid.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/pack/operation/EntitySelectPane.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageExport.java, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/pack/PackageService.java, iplass-tools/src/main/resources/mtp-tools-messages.properties, iplass-tools/src/main/resources/mtp-tools-messages_en.properties, iplass-tools/src/main/resources/mtp-tools-messages_ja.properties
Export時にPackageエンティティを除外する。
#44 対応。
=> Package、Packageエンティティを対象外にする

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/boolean/BooleanPropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/date/DatePropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/time/TimePropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/timestamp/TimestampPropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/resource.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
#74 対応。
NestTableのPropertyEditorのLabelモード表示不具合の改善。
=> ReferencePropertyEditorのNestTable、EditorをLabel表示すると正しく表示されない

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
https://github.com/ISID/iPLAss/issues/100 対応。
１次対応した結果ダイアログは起動するようになっているが、以下の処理がうまくいっていないため改善。
・キャンセル処理がうまく動いていない。確認メッセージが２度実行され、エラーになってしまう。
・編集ダイアログで保存後、再度編集を実行しても起動されない。
=> ダイアログのNestTableの編集リンクが動かない

iplass-core/src/main/java/org/iplass/mtp/impl/lob/LobDao.java, iplass-core/src/main/java/org/iplass/mtp/impl/lob/LobHandler.java, iplass-core/src/main/java/org/iplass/mtp/impl/lob/LobStoreService.java, iplass-core/src/main/java/org/iplass/mtp/impl/lob/sql/BlobSearchSql.java, iplass-core/src/main/java/org/iplass/mtp/impl/lob/sql/LobStoreSearchSql.java, iplass-core/src/main/resources/mtp-core-service-config.xml
#95 対応。
LobStoreServiceに設定を追加する。
=> LobCleanerバッチで削除対象するLobの日付を指定可能にする

iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntityCsvReader.java, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entityport/EntityPortingService.java
https://github.com/ISID/iPLAss/issues/124 対応。
=> Package、インポート時のOIDPrefixが効かない

iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_en.js, iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_ja.js, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaSearchResultSection.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/section/SearchResultSection.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection.jsp
Entity検索画面、検索結果（jqgrid）の高さを設定できるように #112
=> Entity検索画面、検索結果（jqgrid）の高さを設定できるように #112

iplass-gem/src/main/java/org/iplass/gem/GemConfigService.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/FormViewUtil.java, iplass-gem/src/main/resources/gem-service-config.xml
Entity検索画面、検索結果の件数のデフォルト値を設定ファイルにて設定可能に #113
=> Entity検索画面、検索結果の件数のデフォルト値を設定ファイルにて設定可能に #113

iplass-core/src/main/java/org/iplass/mtp/impl/information/InformationEntityEventListener.java, iplass-core/src/main/resources/mtp-core-metadata.xml
お知らせ情報Entity、有効終了日を自動補完する
#115
=> お知らせ情報Entity、有効終了日を自動補完する #115

iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/BulkCommandContext.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/BulkUpdateListCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/BulkUpdateViewCommand.java
バージョン管理されているエンティティを一括更新可能に #143
=> バージョン管理されているエンティティを一括更新可能に #143

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Table.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/flat/design.js
参照プロパティの新規ボタン、追加ボタンの表示制御
https://github.com/ISID/iPLAss/issues/114
=> 参照プロパティの新規ボタン、追加ボタンの表示制御

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/date/DatePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/string/StringPropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/time/TimePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/timestamp/TimestampPropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
・プロパティ値の数がマルチプロパティの多重度設定値を超えた場合、追加ボタンを非表示に
・プロパティ値の数がマルチプロパティの多重度設定値より小さい場合、追加ボタンを表示に
=> マルチプロパティの新規ボタン、追加ボタンの表示制御 #155

iplass-tools-batch/src/main/bat/eql_execute.bat, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EQLExecutor.java, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages.properties, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_en.properties, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_ja.properties, iplass-tools-batch/src/main/sh/eql_execute.sh, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entity/EntityToolService.java, iplass-tools/src/main/resources/mtp-tools-messages.properties, iplass-tools/src/main/resources/mtp-tools-messages_en.properties, iplass-tools/src/main/resources/mtp-tools-messages_ja.properties
=> EQLをCLIで実行できるようにする

iplass-gem/src/main/java/org/iplass/gem/command/Constants.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/view.jsp
#173 の対応
・詳細画面に遷移元が詳細画面であるか判断フラグを追加。
=> #173 Entity編集画面、キャンセル押下時の戻り先画面の改善

iplass-admin/src/main/java/org/iplass/adminconsole/server/base/service/AdminEntityManager.java, iplass-core/src/main/java/org/iplass/mtp/entity/EntityManager.java, iplass-core/src/main/java/org/iplass/mtp/impl/entity/EntityManagerImpl.java
https://github.com/ISID/iPLAss/issues/187
の対応
=> #187 全文検索、DB（Entity）検索と組み合わせる場合の適用順を変えたメソッドを提供

iplass-tools-batch/src/main/bat/service_config_view.bat, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/config/ServiceConfigViewer.java, iplass-tools-batch/src/main/sh/service_config_view.sh
=> service-configのマージ結果を出力するツール #183

iplass-admin/build.gradle, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/EntityViewFieldSettingPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/property/PropertyControl.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/SectionControllerImpl.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/metafield/MetaFieldSettingDialog.java, iplass-admin/src/main/java/org/iplass/adminconsole/server/metadata/rpc/MetaDataServiceImpl.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/HasMetaNestProperty.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaJoinPropertyEditor.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaReferencePropertyEditor.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaDefaultSection.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaMassReferenceSection.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/HasNestProperty.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/editor/JoinPropertyEditor.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/editor/ReferencePropertyEditor.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/section/MassReferenceSection.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/section/ReferenceSection.java
=> 参照プロパティでJoinPropertyEditorを利用する場合、編集ダイアログのプロパティリストに参照元のものが表示されてしまう

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/SectionControllerImpl.java
・Bulk Viewレイアウト定義画面のElementに標準セクションを表示します。
=> #255 一括更新、複数項目を指定して一括更新する機能の調整

iplass-gem/src/main/java/org/iplass/gem/command/generic/common/GetEntityNameListCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/refunique/GetReferenceUniqueItemCommand.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/editor/PropertyEditor.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/editor/ReferencePropertyEditor.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Condition.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/sass/flat/module/generic/detail/_detail.scss
=> #254 ユニークキーの入力フィールド機能の調整

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
https://github.com/ISID/iPLAss/issues/270 の対応。
=> 参照プロパティの新規ボタンの表示制御漏れ #270

iplass-gem/src/main/java/org/iplass/gem/command/Constants.java, iplass-gem/src/main/java/org/iplass/gem/command/CreateSearchResultUtil.java, iplass-gem/src/main/java/org/iplass/gem/command/ViewUtil.java, iplass-gem/src/main/java/org/iplass/gem/command/fulltext/FullTextSearchCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/common/GetEntityNameListCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/SearchCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/SearchListCommand.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/EntityViewManagerImpl.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/bulk/bulkEdit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/bulk/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/completed.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/view.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/ReferencePropertyEditor.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
=> #250 参照先エンティティを更新した後参照元画面の参照リンクの表示ラベルが正しく更新されない

iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/EQLExecutePane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/ItemControl.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/MassReferenceSectionControl.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/ReferenceSectionControl.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/ScriptingSectionControl.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/SectionControl.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/TemplateSectionControl.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/VersionSectionControl.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/eql/EqlWorksheetMainPane.java
https://github.com/ISID/iPLAss/issues/230 対応。
=> AdminConsole、レイアウト調整

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/LoadEntityInterrupterHandler.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/RegistrationCommandContext.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/LoadEntityInterrupter.java
https://github.com/ISID/iPLAss/issues/296 対応
・LoadEntityInterrupterにbeforeSearchMassReference、afterSearchMassReferenceを追加
・LoadEntityInterrupterのbeforeLoadEntity、beforeLoadReferenceにデフォルト実装を定義
=> gem、大量データセクションの検索時にフックポイントを提供する

iplass-gem/src/main/java/org/iplass/gem/command/Constants.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/common/GetEntityNameListCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/common/GetEntityNameListParameter.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/EntityViewManagerImpl.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/EntityViewManager.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/completed.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/view.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/ReferenceSection.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/webapi.js
=> #302 参照セクションで参照項目の名前が取得できない 

iplass-gem/src/main/java/org/iplass/gem/command/CreateSearchResultUtil.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/EntityViewManagerImpl.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/ReferencePropertyEditor.jsp
大量データ参照セクションで参照項目の名前が取得できない #316
=> 大量データ参照セクションで参照項目の名前が取得できない #316

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyAutocompletion.jsp
=> 参照プロパティエディターの自動補完機能の利用で編集画面で多重度以上のデータを追加できてしまう #284

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/Password.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/bulk/bulkEdit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/bulk/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/view.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/view.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Condition.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Condition_Nest.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_RefCombo.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Table.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/property/Property.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/property/PropertyColumn.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/ReferenceSection.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchConditionSection.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/search/search.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/search/select.jsp
=> Editor系ViewNameの参照元をAttribute参照に変更します

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/action/ActionAttributePane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/webapi/WebApiAttributePane.java, iplass-web/src/main/java/org/iplass/mtp/command/annotation/action/ActionMapping.java, iplass-web/src/main/java/org/iplass/mtp/impl/web/WebUtil.java, iplass-web/src/main/java/org/iplass/mtp/impl/web/actionmapping/MetaActionMapping.java, iplass-web/src/main/java/org/iplass/mtp/impl/web/actionmapping/MetaActionMappingFactory.java, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/rest/RestCommandInvoker.java, iplass-web/src/main/java/org/iplass/mtp/web/actionmapping/definition/ClientCacheType.java, iplass-web/src/main/java/org/iplass/mtp/webapi/definition/CacheControlType.java
=> ActionおよびWebAPI、クライアントキャッシュの種別にCACHE_PUBLICを追加

iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/layout/AdminMenuTreeGrid.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/layout/AdminMenuTreeNode.java, iplass-admin/src/main/resources/org/iplass/adminconsole/public/mtpadmin.css
https://github.com/ISID/iPLAss/issues/349 対応
=> AdminConsole、画面のzoom設定によってメニューのアイコンが表示されない

iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_en.js, iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_ja.js, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaMassReferenceSection.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/section/MassReferenceSection.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/MassReferenceSection.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/sass/flat/module/generic/_common.scss
=> feature/#358-update-massReference-data-dynamically 

iplass-gem/.gitignore, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/sass/flat/module/generic/search/_parts.scss, iplass-gem/src/main/sass/flat/module/generic/search/_search.scss, iplass-gem/src/main/sass/flat/module/plugins/_jqgrid.scss
https://github.com/ISID/iPLAss/issues/407 対応
=> 検索結果一覧、画面のzoom設定によって棒線が表示されないことがある

iplass-core/src/main/java/org/iplass/mtp/impl/datastore/grdb/strategy/GRdbApplyMetaDataStrategy.java, iplass-tools-batch/src/main/bat/meta_data_patch.bat, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataPatch.java, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages.properties, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_en.properties, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_ja.properties, iplass-tools-batch/src/main/sh/meta_data_patch.sh, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/metaport/MetaDataPortingService.java, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/metaport/MetaDataPortingServiceImpl.java, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/metaport/PatchEntityDataParameter.java, iplass-tools/src/main/resources/mtp-tools-service-config.xml
ファイルベースのメタデータ変更に伴うEntityデータのパッチsh/batの提供
=> #438 メタデータパッチ

iplass-admin/src/main/java/org/iplass/adminconsole/server/base/service/AdminEntityManager.java, iplass-core/src/main/java/org/iplass/mtp/entity/DeepCopyOption.java, iplass-core/src/main/java/org/iplass/mtp/entity/EntityManager.java, iplass-core/src/main/java/org/iplass/mtp/impl/entity/EntityManagerImpl.java, iplass-gem/src/main/java/org/iplass/gem/GemConfigService.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailViewCommand.java
=> gem、Entityのコピー操作時にバイナリデータ本体はコピーしないモードを指定可能に

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/menu/MenuTreeGrid.java
adminConsole、メニューからEntityViewの参照を把握しやすくする #493
=> adminConsole、メニューからEntityViewの参照を把握しやすくする。

iplass-core/src/main/java/org/iplass/mtp/impl/rdb/adapter/NoopRdbAdapter.java, iplass-core/src/main/java/org/iplass/mtp/impl/rdb/adapter/RdbAdapter.java, iplass-core/src/main/java/org/iplass/mtp/impl/rdb/mysql/MysqlRdbAdaptor.java, iplass-core/src/main/java/org/iplass/mtp/impl/rdb/oracle/OracleRdbAdapter.java, iplass-core/src/main/java/org/iplass/mtp/impl/rdb/postgresql/PostgreSQLRdbAdapter.java, iplass-core/src/main/java/org/iplass/mtp/impl/rdb/sqlserver/SqlServerRdbAdapter.java, iplass-tools-batch/src/main/bat/entity_view_ddl.bat, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityViewDDLCreator.java, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages.properties, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_en.properties, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_ja.properties, iplass-tools-batch/src/main/sh/entity_view_ddl.sh, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entity/EntityToolService.java, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entity/EntityViewDDLWriter.java
=> Entityに対応するRDB上でのViewを作成するツール

iplass-admin/build.gradle, iplass-admin/libs.gradle, iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/ScriptEditorDialog.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/MultiColumnDropLayout.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/staticresource/StaticResourceUploadPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/template/BinaryTemplateEditPane.java, iplass-admin/src/main/resources/META-INF/resources/jsp/admin/main.jsp, iplass-admin/src/main/resources/org/iplass/gwt/ace/GwtAce.gwt.xml, lib/.gitignore, lib/smartgwt/note.txt, sharedlibs.gradle
https://github.com/ISID/iPLAss/issues/570 対応
=> GWT系ライブラリバージョンアップ

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/view.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/view.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchConditionSection_CsvDownloadDialog.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/header.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
ダイアログ（jQueryUIベース）表示時に起動元の画面スクロールを防 ぐ #531
=> ダイアログ（jQueryUIベース）表示時に起動元の画面スクロールを防ぐ

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Table.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/ReferenceSection.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
https://github.com/ISID/iPLAss/issues/593 対応
=> NestPropertyのHidden対応

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/boolean/BooleanPropertyEditor_Condition.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/select/SelectPropertyEditor_Condition.jsp
=> 検索条件設定のSelectPropertyEditor、BooleanPropertyEditorのradio形式で必須指定の場合は未選択を表示しない

iplass-core/src/main/java/org/iplass/mtp/impl/command/RequestContextBinding.java
=> RequestContextBindingにgetParam(String)、getParams(String)を定義

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Table.jsp
=> ネストテーブルで多重度*の時、行追加時にボタンが消える

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/fulltext/search.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/MassReferenceSection.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/search/list.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/webapi.js
https://github.com/ISID/iPLAss/issues/597 対応
=> gem画面上でoidを正しくエンコード処理する

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
=> ダイアログ（jQueryUIベース）の改善

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/menu/CreateMenuTreeDialog.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/menu/MenuEditPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/langexplorer/LangExplorerSettingControllerImpl.java, iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_en.js, iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_ja.js, iplass-gem/src/main/java/org/iplass/gem/command/MenuCommand.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/menu/MetaTreeMenu.java, iplass-gem/src/main/java/org/iplass/mtp/view/menu/MenuTree.java
=> メニューの表示名、メニュー定義の表示名を利用可能に

iplass-core/src/main/java/org/iplass/mtp/entity/definition/properties/SelectProperty.java, iplass-core/src/main/java/org/iplass/mtp/entity/definition/properties/selectvalue/SelectValueDefinitionManager.java, iplass-core/src/main/java/org/iplass/mtp/impl/i18n/I18nUtil.java, iplass-core/src/main/java/org/iplass/mtp/impl/properties/extend/select/SelectValueDefinitionManagerImpl.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/RegistrationCommandContext.java
=> RegistrationInterrupterで渡されるEntityのSelect型プロパティの値に表示名もセットする

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/UpdateTableOrderCommand.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Table.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
=> ネストテーブルの表示順が正しく設定されない

iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/data/entityexplorer/SimpleEntityInfoDS.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/entityexplorer/datalist/EntityListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/server/tools/rpc/entityexplorer/EntityExplorerServiceImpl.java, iplass-admin/src/main/java/org/iplass/adminconsole/shared/tools/dto/entityexplorer/SimpleEntityInfo.java
=> EntityExplorer、Entityの一覧にBulkLayout設定、管理設定も出力する

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/property/PropertyControl.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaAutoNumberPropertyEditor.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaExpressionPropertyEditor.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/FormViewUtil.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/editor/AutoNumberPropertyEditor.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/editor/ExpressionPropertyEditor.java
=> AutoNumberPropertyEditor、ExpressionPropertyEditorの表示タイプに「TEXT」を追加

iplass-gem/src/main/java/org/iplass/gem/command/binary/UploadCommand.java
=> ファイルアップロード、アップロード時にSystemExceptionが発生するとエラーが表示されずローディング中のままになる

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/auth/property/AccountLockoutPolicySettingPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/auth/property/PasswordPolicySettingPane.java, iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_en.js, iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_ja.js, iplass-core/src/main/java/org/iplass/mtp/auth/policy/definition/PasswordPolicyDefinition.java, iplass-core/src/main/java/org/iplass/mtp/impl/auth/authenticate/builtin/BuiltinAuthenticationProvider.java, iplass-core/src/main/java/org/iplass/mtp/impl/auth/authenticate/builtin/policy/MetaAuthenticationPolicy.java, iplass-core/src/main/java/org/iplass/mtp/impl/auth/authenticate/builtin/policy/MetaPasswordPolicy.java
=> ビルトインの認証プロバイダ、パスワードポリシーで制御可能項目の拡充

iplass-gem/src/main/java/org/iplass/mtp/view/generic/EntityViewUtil.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Table.jsp
=> 入力エラー時にネストテーブルのデータが消える

iplass-core/src/main/java/org/iplass/mtp/impl/properties/PropertySerializeUtil.java
https://github.com/ISID/iPLAss/issues/638 対応
=> バイナリのシリアライズ、ファイル名も含める

iplass-gem/src/main/java/org/iplass/gem/GemConfigService.java, iplass-gem/src/main/java/org/iplass/gem/command/ViewUtil.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/bulk/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/edit.jsp, iplass-gem/src/main/resources/gem-service-config.xml, iplass-gem/src/main/resources/mtp-gem-messages.properties, iplass-gem/src/main/resources/mtp-gem-messages_en.properties, iplass-gem/src/main/resources/mtp-gem-messages_ja.properties, iplass-gem/src/main/resources/mtp-gem-messages_th.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh_HK.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh_TW.properties
=> gem、Entity操作画面で保存時に確認ダイアログを表示可能に

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
=> gem検索画面、検索結果のページング表示の改善

iplass-tools-batch/src/main/conf/pack-exp-config.properties, iplass-tools-batch/src/main/conf/pack-imp-config.properties, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageExportParameter.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageImport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageImportParameter.java, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages.properties, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_en.properties, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_ja.properties, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/pack/PackageService.java
https://github.com/ISID/iPLAss/issues/677 対応
=> PackageExport、Importバッチ、Package管理せずに直接ファイル実行可能にする

iplass-core/src/main/java/org/iplass/mtp/impl/cache/store/CacheStore.java, iplass-core/src/main/java/org/iplass/mtp/impl/cache/store/builtin/IndexedCacheStoreWrapper.java, iplass-core/src/main/java/org/iplass/mtp/impl/cache/store/builtin/MapBaseCacheStore.java, iplass-core/src/main/java/org/iplass/mtp/impl/cache/store/builtin/NullCacheStore.java, iplass-core/src/main/java/org/iplass/mtp/impl/cache/store/builtin/RdbCacheStoreFactory.java, iplass-core/src/main/java/org/iplass/mtp/impl/cache/store/builtin/SimpleCacheStoreFactory.java, iplass-core/src/main/java/org/iplass/mtp/impl/cache/store/builtin/SyncServerCacheStoreFactory.java, iplass-core/src/main/java/org/iplass/mtp/impl/cache/store/builtin/TransactionLocalCacheStoreFactory.java, iplass-infinispan/src/main/java/org/iplass/mtp/impl/infinispan/cache/store/InfinispanCacheStoreFactory.java, iplass-infinispan/src/main/java/org/iplass/mtp/impl/infinispan/cache/store/InfinispanIndexedCacheStore.java, iplass-redis/src/main/java/org/iplass/mtp/impl/redis/cache/store/RedisCacheStore.java, iplass-redis/src/main/java/org/iplass/mtp/impl/redis/cache/store/RedisIndexedCacheStore.java
=> CacheStoreインタフェースにgetSize()実装

iplass-admin/build.gradle, iplass-admin/src/main/java/gwtupload/client/BaseUploadStatus.java
https://github.com/ISID/iPLAss/issues/710 対応
=> AdminConsole、ファイルアップロードに対するセキュリティ対応

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/binary/BinaryPropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
https://github.com/ISID/iPLAss/issues/708 対応
=> BinaryPropertyEditor、画像回転機能の改善

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/auth/property/PasswordPolicySettingPane.java, iplass-core/src/main/java/org/iplass/mtp/auth/policy/definition/PasswordPolicyDefinition.java, iplass-core/src/main/java/org/iplass/mtp/impl/auth/authenticate/builtin/BuiltinAuthenticationProvider.java, iplass-core/src/main/java/org/iplass/mtp/impl/auth/authenticate/builtin/policy/MetaPasswordPolicy.java, iplass-core/src/main/resources/mtp-core-metadata.xml
=> パスワード履歴保持、保持数ではなく保持期間も指定可能とする

iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/MultiBulkCommandContext.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/NestTableReferenceRegistHandler.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/NestTableRegistOption.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/ReferenceRegistHandlerBase.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/ReferenceRegistOption.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/ReferenceSectionReferenceRegistHandler.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/RegistrationInterrupterHandler.java
=> カスタム登録処理、NestTableの更新項目も制御可能にする 

iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_en.js, iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_ja.js, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaUserPropertyEditor.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/editor/UserPropertyEditor.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/UserPropertyEditor.jsp
https://github.com/ISID/iPLAss/issues/730 対応
=> UserPropertyEditor、Hiddenモードを追加

iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CSVDownloadSearchViewWriter.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CsvDownloadSearchContext.java, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
https://github.com/ISID/iPLAss/issues/732 対応
=> UserPropertyEditor、CSVダウンロード時に作成者、更新者、ロックユーザ以外でも名称出力可能に

iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CSVDownloadSearchViewWriter.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CsvDownloadSearchContext.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CsvDownloadUploadableWriter.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/MetaVirtualProperty.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/CsvItem.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/VirtualPropertyItem.java
https://github.com/ISID/iPLAss/issues/743 対応
=> CSVダウンロード、仮想プロパティも出力可能にする

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/menu/menu.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/flat/design.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/horizontal/design.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/vertical/design.js
=> cookieからsessionStorageに変更

iplass-gem/src/main/java/org/iplass/gem/command/generic/search/SearchContextBase.java
=> 検索結果画面、参照プロパティのソートの挙動修正

iplass-gem/src/main/java/org/iplass/gem/command/generic/search/SearchContextBase.java
=> 検索結果画面、参照プロパティのソートの挙動修正（3.0）

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/flat/design.js
=> gem、フラットスキン、検索画面で検索条件項目が多い場合のスクロール考慮

iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/sass/flat/module/generic/detail/_detail.scss, iplass-gem/src/main/sass/flat/module/treeview/_parts.scss
=> フラットデザイン、検索結果一覧でのReference項目がリンクであることをわかりやすくする

iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/blue/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/green/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/lightblue/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/lightgreen/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/lightred/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/orange/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/red/color.css, iplass-gem/src/main/sass/flat/module/plugins/_jqgrid.scss, iplass-gem/src/main/sass/flat/theme/_theme.scss
https://github.com/ISID/iPLAss/issues/778 の対応
=> jqGrid、表内のテキスト選択時の背景色変更

iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/structure.css, iplass-gem/src/main/sass/flat/structure/_headermenu.scss
=> フラットデザイン、右肩メニューのクリック有効範囲を調整

iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/MultiBulkUpdateListCommand.java
=> BulkLayoutを用いた一括更新において、被参照プロパティのNestTableを利用した更新で不具合修正

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp
=> gem、ファイルアップロード時のエラーメッセージを赤色で表示する

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/fulltext/search.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/search/list.jsp
=> gem、検索画面での詳細リンク、編集リンクのツールチップ文言の改善

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchConditionSection_CsvDownloadDialog.jsp, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/blue/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/green/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/lightblue/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/lightgreen/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/lightred/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/orange/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/red/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/theme/blue/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/theme/green/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/theme/lightblue/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/theme/lightgreen/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/theme/lightred/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/theme/orange/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/theme/red/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/theme/blue/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/theme/green/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/theme/lightblue/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/theme/lightgreen/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/theme/lightred/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/theme/orange/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/theme/red/color.css, iplass-gem/src/main/sass/basedesign/module/common/_modal.scss, iplass-gem/src/main/sass/basedesign/theme/_theme.scss, iplass-gem/src/main/sass/flat/module/common/_modal.scss, iplass-gem/src/main/sass/flat/theme/_theme.scss
=> gem、CSVダウンロード時の形式選択ダイアログのCSVダウンロードボタンを目立たせる改善

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/module/calendar/calendar.js
=> gem、cookieへの保存をsessionStorageへ

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java
https://github.com/ISID/iPLAss/issues/809 対応
=> LABEL形式のPropertyEditorの更新処理、Entityに値をセットした上でOptionから除外する

iplass-core/src/main/java/org/iplass/mtp/impl/datastore/grdb/StorageSpaceMap.java, iplass-core/src/main/resources/mtp-core-service-config-aurora_mysql.xml, iplass-core/src/main/resources/mtp-core-service-config-mysql-5.7.xml, iplass-core/src/main/resources/mtp-core-service-config-mysql.xml, iplass-core/src/main/resources/mtp-core-service-config-mysql_pseudo_128.xml, iplass-core/src/main/resources/mtp-core-service-config-oracle_pseudo.xml, iplass-core/src/main/resources/mtp-core-service-config-oracle_pseudo_128.xml, iplass-core/src/main/resources/mtp-core-service-config-postgre_pseudo.xml, iplass-core/src/main/resources/mtp-core-service-config-postgre_pseudo_128.xml, iplass-core/src/main/resources/mtp-core-service-config-sqlserver_pseudo.xml, iplass-core/src/main/resources/mtp-core-service-config-sqlserver_pseudo_128.xml, iplass-core/src/main/resources/mtp-core-service-config.xml, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/storagespace/StorageSpaceServiceImpl.java
=> storage_space_migrateバッチ&clean_storage_spaceバッチ：mtp、userから削除する場合エラー

iplass-core/src/main/java/org/iplass/mtp/impl/datastore/grdb/sql/RecycleBinSql.java
=> ごみ箱から削除データ取得時のソート順を削除時の降順にする

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/calendarResource.inc.jsp, sharedlibs.gradle
=> fullcalendarバージョンアップ

iplass-tools-batch/src/main/bat/eql_execute.bat, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EQLExecutor.java, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages.properties, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_en.properties, iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_ja.properties, iplass-tools-batch/src/main/sh/eql_execute.sh
=> EQL ExecutorバッチにCSV出力モード追加

iplass-core/src/main/resources/schema/sql/ddl/mysql/obj_blob.sql, iplass-core/src/main/resources/schema/sql/ddl/mysql/obj_blob_rb.sql, iplass-core/src/main/resources/schema/sql/ddl/mysql_compress/obj_blob.sql, iplass-core/src/main/resources/schema/sql/ddl/mysql_compress/obj_blob_rb.sql, iplass-core/src/main/resources/schema/sql/ddl/mysql_pseudo_128/obj_blob.sql, iplass-core/src/main/resources/schema/sql/ddl/mysql_pseudo_128/obj_blob_rb.sql
=> mysql（aurora）のobj_blobテーブルのindex（pk）の変更

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/property/type/AutoNumberValueListDialog.java
=> AdminConosleからCurrentValueのリセットが9007199254740991超の値でできない

iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/sass/flat/module/information/_list.scss
=> GEM、Flatデザインの場合、Information Listの”Scroll display number”が効かない

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/coreResource.inc.jsp, sharedlibs.gradle
=> Moment.jsバージョンアップ

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/LoadEntityInterrupterHandler.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/NestTableReferenceRegistHandler.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/ReferenceRegistHandlerBase.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/ReferenceSectionReferenceRegistHandler.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/LoadEntityInterrupter.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Table.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/ReferenceSection.jsp
=> LoadEntityInterrupterでView定義のElement/Sectionを判別可能にする

iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/MetaDetailFormView.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaReferencePropertyEditor.java
=> MetaとDefinitionの変換時にディープコピーされていないプロパティがある

iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/MetaDetailFormView.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/MetaSearchFormView.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaReferencePropertyEditor.java
=> MetaとDefinitionの変換時にディープコピーされていないプロパティがある（3.0）

iplass-core/src/main/java/org/iplass/mtp/impl/util/UploadFileUtil.java, iplass-test/src/main/java/org/iplass/mtp/test/TestUploadFileHandle.java, iplass-web/build.gradle, iplass-web/src/main/java/org/iplass/mtp/impl/web/WebFrontendService.java, iplass-web/src/main/java/org/iplass/mtp/impl/web/fileupload/DefaultMagicByteChecker.java, iplass-web/src/main/java/org/iplass/mtp/impl/web/fileupload/MagicByteChecker.java, iplass-web/src/main/java/org/iplass/mtp/impl/web/fileupload/MagicByteRule.java, iplass-web/src/main/java/org/iplass/mtp/impl/web/fileupload/MagicByteRuleCondition.java, iplass-web/src/main/java/org/iplass/mtp/impl/web/fileupload/UploadFileHandleImpl.java, iplass-web/src/main/resources/mtp-web-service-config.xml, sharedlibs.gradle
=> ファイルアップロード時のマジックバイトチェックの改善

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/SearchContextBase.java
https://github.com/ISID/iPLAss/issues/867 対応
=> gem、UserPropertyEditorでロックユーザ、作成者、更新者がViewにないとユーザ名が出力されない

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/coreResource.inc.jsp, sharedlibs.gradle
https://github.com/ISID/iPLAss/issues/912 対応
=> Moment.jsを2.29.4にバージョンアップ（3.1）

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/coreResource.inc.jsp, sharedlibs.gradle
https://github.com/ISID/iPLAss/issues/913 対応
=> Moment.jsを2.29.4にバージョンアップ（3.2）

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/Expire.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/Login.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/ReAuth.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/error/Error.jsp
https://github.com/ISID/iPLAss/issues/919 対応
=> エラーメッセージの出力方法改善（3.2）

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/Expire.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/Login.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/ReAuth.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/error/Error.jsp
https://github.com/ISID/iPLAss/issues/920 対応
=> エラーメッセージの出力方法改善（3.1）

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/Expire.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/Login.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/ReAuth.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/error/Error.jsp
https://github.com/ISID/iPLAss/issues/921 対応
=> エラーメッセージの出力方法改善（3.0）

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/time/TimePropertyEditor_Condition.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/time/TimePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/timestamp/TimestampPropertyEditor_Condition.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/timestamp/TimestampPropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
=> gem画面、日時・時間型で入力チェックエラー(3.1)

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/time/TimePropertyEditor_Condition.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/time/TimePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/timestamp/TimestampPropertyEditor_Condition.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/timestamp/TimestampPropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
=> gem画面、日時・時間型で入力チェックエラー

iplass-core/src/main/resources/schema/sql/ddl/mysql/obj_blob_rb.sql, iplass-core/src/main/resources/schema/sql/ddl/mysql_compress/obj_blob_rb.sql, iplass-core/src/main/resources/schema/sql/ddl/mysql_pseudo_128/obj_blob_rb.sql
=> mysql（aurora）のobj_blob_rbテーブルのindex（pk）の変更

sharedlibs.gradle
https://github.com/ISID/iPLAss/issues/945 対応
=> Groovyバージョンアップ

sharedlibs.gradle
https://github.com/ISID/iPLAss/issues/946 対応
=> Groovyバージョンアップ（3.1）

iplass-web/src/main/java/org/iplass/mtp/impl/csv/CsvUploadService.java
https://github.com/ISID/iPLAss/issues/933 対応
=> GEM、CSVアップロードで_useCtrlで削除時にUniqueKey指定で削除可能にする

iplass-web/src/main/java/org/iplass/mtp/impl/csv/CsvUploadService.java
https://github.com/ISID/iPLAss/issues/934 対応
=> GEM、CSVアップロードで_useCtrlで削除時にUniqueKey指定で削除可能にする（3.1）

iplass-gem/src/main/java/org/iplass/gem/command/generic/delete/DeleteCommandContext.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/webapi.js
=> gem、バージョン管理されているEntityの検索画面での一括削除処理改善

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/Password.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/specificPassword.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/bulk/bulkEdit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/bulk/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/editButton.inc.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/editButton.inc.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/view.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/upload/csvUpload.jsp
https://github.com/ISID/iPLAss/issues/956 対応
=> gem、画面描写後にボタンを押下可能にする

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/Password.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/auth/specificPassword.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/bulk/bulkEdit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/bulk/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/editButton.inc.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/editButton.inc.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/view.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/upload/csvUpload.jsp
https://github.com/ISID/iPLAss/issues/962 対応
=> gem、画面描写後にボタンを押下可能にする（3.1）

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/property/NormalizerListGrid.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/property/PropertyEditDialog.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/property/ValidationListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/property/type/SortInfoListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/server/metadata/rpc/refrect/RefrectionServiceImpl.java
https://github.com/ISID/iPLAss/issues/967 対応
=> AdminConsole、Entityの編集画面のレイアウト改善

iplass-core/src/main/java/org/iplass/mtp/impl/core/config/DecodePreprocessor.java, iplass-core/src/main/java/org/iplass/mtp/impl/core/config/DefaultPropertyValueCoder.java, iplass-core/src/main/java/org/iplass/mtp/impl/core/config/PropertyValueCoder.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/crypt/Encoder.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/crypt/EncoderConsolePassphraseSupplier.java
=> 設定値の難読化：PropertyValueCoderの実装クラスを指定可能にする

iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CSVDownloadSearchViewWriter.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/section/SearchConditionSection.java
https://github.com/ISID/iPLAss/issues/984 の対応
=> gem、検索条件設定の「CSVダウンロード件数の上限値」が保存できない（3.1）

iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CSVDownloadSearchViewWriter.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/section/SearchConditionSection.java
https://github.com/ISID/iPLAss/issues/981 の対応
=> gem、検索条件設定の「CSVダウンロード件数の上限値」が保存できない

sharedlibs.gradle
=> Luceneライブラリバージョンアップ

iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntitySearchCsvWriter.java, iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntityWriteOption.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CSVDownloadSearchViewWriter.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CsvDownloadUploadableWriter.java
=> gem、バージョン管理されているEntityのCSVダウンロード時に検索条件の「すべてのバージョン」フラグを考慮する

iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntitySearchCsvWriter.java, iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntityWriteOption.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CSVDownloadSearchViewWriter.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CsvDownloadUploadableWriter.java
https://github.com/ISID/iPLAss/issues/1004 の対応
=> gem、バージョン管理されているEntityのCSVダウンロード時に検索条件の「すべてのバージョン」フラグを考慮する（3.1）

iplass-core/src/main/java/org/iplass/mtp/impl/properties/extend/LongTextType.java
https://github.com/ISID/iPLAss/issues/986 対応
=> LongText、多重度複数の場合にnull値が含まれるとエラーになる

iplass-gem/src/main/java/org/iplass/mtp/impl/view/top/TopViewDefinitionManagerImpl.java
https://github.com/ISID/iPLAss/issues/995 対応
=> お知らせ情報詳細画面のメニュー制御対応

iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entityport/EntityPortingService.java
https://github.com/ISID/iPLAss/issues/1015 対応
=> バージョン管理判定の不具合対応

iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entityport/EntityPortingService.java
https://github.com/ISID/iPLAss/issues/1016 対応
=> バージョン管理判定の不具合対応（3.1）

iplass-web/libs.gradle, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/MetaWebApi.java
=> CORSの許可するドメイン設定でサブドメインの許可を簡易に設定できるようにする

iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/AbstractFulltextSeachService.java, iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/AbstractFulltextSearchService.java, iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/IndexedEntity.java, iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/TempEntityList.java, iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/lucene/LuceneFulltextSearchService.java, iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/sql/CrawlLogSearchSql.java, iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/sql/DeleteLogSearchSql.java, iplass-core/src/main/resources/mtp-core-service-config.xml
=> 全文検索、処理の共通化

iplass-gem/src/main/java/org/iplass/gem/command/generic/common/GetEntityNameListCommand.java
https://github.com/ISID/iPLAss/issues/1029 対応
=> gem、ReferencePropertyEditorの表示ラベルにoidを指定すると正常に動作しない（3.1）

iplass-gem/src/main/java/org/iplass/gem/command/generic/common/GetEntityNameListCommand.java
https://github.com/ISID/iPLAss/issues/980 対応
=> gem、ReferencePropertyEditorの表示ラベルにoidを指定すると正常に動作しない

iplass-admin/src/main/resources/org/iplass/adminconsole/AdminConsole.gwt.xml, iplass-admin/src/main/resources/org/iplass/adminconsole/AdminConsoleBase.gwt.xml, iplass-admin/src/main/resources/org/iplass/gwt/ace/GwtAce.gwt.xml
https://github.com/ISID/iPLAss/issues/1026 対応。
httpsに変更。
バージョン変更漏れ対応。
=> gwt-module.dtd対応

iplass-core/src/main/java/org/iplass/mtp/entity/EntityManager.java
=> BulkUpdateの場合のバージョン管理時はバージョン番号を明示的に指定必要なことをどこかに注意書きしておく

iplass-web/src/main/java/org/iplass/mtp/impl/csv/CsvUploadService.java
=> 更新不可項目があるエンティティでCSVアップロードするとエラーが発生

iplass-web/src/main/java/org/iplass/mtp/impl/csv/CsvUploadService.java
https://github.com/ISID/iPLAss/issues/1054 対応
=> 更新不可項目があるエンティティでCSVアップロードするとエラーが発生（3.1）

iplass-admin/src/main/resources/org/iplass/adminconsole/AdminConsole.gwt.xml, iplass-admin/src/main/resources/org/iplass/adminconsole/AdminConsoleBase.gwt.xml, iplass-admin/src/main/resources/org/iplass/gwt/ace/GwtAce.gwt.xml
https://github.com/ISID/iPLAss/issues/1058 対応
=> GWT、module.xmlの警告対応

build.gradle
=> javadoc 出力対象の調整（gem, test）

build.gradle
=> javadoc 出力対象の調整（gem, test）（3.1）

iplass-gem/src/main/java/org/iplass/gem/command/fulltext/FullTextSearchCommand.java
=> GEM全文検索、参照プロパティのソート時のキーを画面上の表示項目にする

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/string/StringPropertyEditor_View.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/information/view.jsp
https://github.com/ISID/iPLAss/issues/1067 対応
=> gem、RichTextEditorの表示モードの領域のレイアウトを調整

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/resources/mtp-gem-messages.properties, iplass-gem/src/main/resources/mtp-gem-messages_en.properties, iplass-gem/src/main/resources/mtp-gem-messages_ja.properties, iplass-gem/src/main/resources/mtp-gem-messages_th.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh_HK.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh_TW.properties, iplass-gem/src/main/sass/flat/module/generic/search/_search.scss
=> gem検索画面、ページ番号入力フィールドの値が不正な場合、エラーメッセージだしたい

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/ApplicationMaintenanceItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/CalendarItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/CsvDownloadSettingsItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/FulltextSearchViewItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/InformationItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/LastLoginItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/PartsItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/PreviewDateItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/ScriptItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/SearchResultListItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/SeparatorItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/TemplateItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/TreeViewItem.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/UserMaintenanceItem.java
https://github.com/ISID/iPLAss/issues/1080 対応
=> AdminConsole、TopViewのパーツをダブルクリックで編集画面を表示する

iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntityCsvReader.java
https://github.com/ISID/iPLAss/issues/1089 対応
=> gem、CSVアップロードにて多重度複数のReferenceプロパティ値が未指定の場合はnullを設定する

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/edit.jsp
https://github.com/ISID/iPLAss/issues/1092 対応
=> gem、編集ダイアログで更新ボタン押下時に数値・日付項目の入力エラーがある場合はアラートを表示する

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/decimal/DecimalPropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/number/NumberPropertyEditor_Edit.jsp
https://github.com/ISID/iPLAss/issues/1094 対応
=> gem、数値系PropertyEditorで多重度分追加した場合に追加ボタンが消えない

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection_Nest.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/search/list.jsp
=> 検索画面で「検索結果をまとめる」指定時、参照がまとまらない

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/date/DatePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/time/TimePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/timestamp/TimestampPropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
https://github.com/ISID/iPLAss/issues/1100 対応
=> gem、NestTable上の数値、日付系PropertyEditorの値チェックが不正

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailViewCommand.java
https://github.com/ISID/iPLAss/issues/1112 対応
=> gem、Entityのコピー時に更新不可プロパティもコピーする

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/search/list.jsp
https://github.com/ISID/iPLAss/issues/1117 対応
=> 検索画面で「検索結果をまとめる」指定時、値がないセルのツールチップ文言を改善

sharedlibs.gradle
- commons-fileupload:commons-fileupload:1.5
=> Apache Commons FileUpload バージョンアップ

iplass-core/src/main/java/org/iplass/mtp/impl/auth/authenticate/builtin/policy/MetaAuthenticationPolicy.java
https://github.com/ISID/iPLAss/issues/1085 対応
=> 認証ポリシー、パスワードポリシーのdeny listでUserエンティティのプロパティ名を指定可能に

iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntitySearchCsvWriter.java, iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntityWriteOption.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CsvDownloadUploadableWriter.java, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entityport/EntityPortingService.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/CsvUploadService.java, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/command/entity/GetEntityCommand.java, iplass-web/src/main/resources/mtp-web-service-config.xml
https://github.com/ISID/iPLAss/issues/1136 対応
=> CSVダウンロード、多重度複数の参照に対する条件が指定されている場合のソート条件を改善（3.1）

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchConditionSection_CsvDownloadDialog.jsp, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/module.css, iplass-gem/src/main/sass/basedesign/module/generic/search/_search.scss, iplass-gem/src/main/sass/flat/module/generic/search/_search.scss
https://github.com/ISID/iPLAss/issues/1141 対応
=> CSVDownloadダイアログ、レイアウト調整

iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntitySearchCsvWriter.java, iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntityWriteOption.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CsvDownloadUploadableWriter.java, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entityport/EntityPortingService.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/CsvUploadService.java, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/command/entity/GetEntityCommand.java, iplass-web/src/main/resources/mtp-web-service-config.xml
https://github.com/ISID/iPLAss/issues/1135 対応
=> CSVダウンロード、多重度複数の参照に対する条件が指定されている場合のソート条件を改善

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchConditionSection_CsvDownloadDialog.jsp, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/module.css, iplass-gem/src/main/sass/basedesign/module/generic/search/_search.scss, iplass-gem/src/main/sass/flat/module/generic/search/_search.scss
https://github.com/ISID/iPLAss/issues/1140 対応
=> CSVダウロードダイアログ、レイアウト調整

iplass-gem/src/main/java/org/iplass/gem/command/generic/upload/CsvSampleDownloadCommand.java
https://github.com/ISID/iPLAss/issues/1143 対応
=> サンプルCSVダウンロードでUpload形式での出力項目をチェックする

iplass-gem/src/main/java/org/iplass/gem/command/generic/upload/CsvSampleDownloadCommand.java
https://github.com/ISID/iPLAss/issues/1144 対応
=> サンプルCSVダウンロードでUpload形式での出力項目をチェックする（3.1）

iplass-gem/src/main/java/org/iplass/gem/EntityViewHelperImpl.java
https://github.com/ISID/iPLAss/issues/1152 対応
=> gem、検索一覧で、多重度複数のプロパティではソートできないようにする

iplass-admin/build.gradle, iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_en.js, iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_ja.js, iplass-gem/src/main/java/org/iplass/gem/command/fulltext/FullTextSearchCommand.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaNestProperty.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/property/MetaPropertyColumn.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/editor/NestProperty.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/SortItem.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/property/PropertyColumn.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/section/SearchResultSection.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection_Nest.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/search/list.jsp, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/module.css, iplass-gem/src/main/sass/basedesign/module/plugins/_jqgrid.scss, iplass-gem/src/main/sass/flat/module/plugins/_jqgrid.scss
https://github.com/ISID/iPLAss/issues/1153 対応
=> gem、検索一覧でソート可能項目を制限可能に

iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/blue/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/green/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/lightblue/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/lightgreen/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/lightred/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/orange/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/theme/red/color.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/module.css, iplass-gem/src/main/sass/basedesign/module/generic/_common.scss, iplass-gem/src/main/sass/basedesign/module/plugins/_jqtree.scss, iplass-gem/src/main/sass/basedesign/module/topview/_widget.scss, iplass-gem/src/main/sass/basedesign/module/treeview/_widget.scss, iplass-gem/src/main/sass/flat/module/generic/_common.scss, iplass-gem/src/main/sass/flat/module/plugins/_jqtree.scss, iplass-gem/src/main/sass/flat/theme/_theme.scss, iplass-gem/src/main/sass/horizontal/module/vars/_urls.scss, iplass-gem/src/main/sass/vertical/module/vars/_urls.scss
https://github.com/ISID/iPLAss/issues/1166 対応
jqtreeを利用している以下の箇所を見直し
- TopView、TreeView widget
- ReferencePropertyEditor Treeタイプ
=> jqtreeのcss見直し

iplass-admin/build.gradle, iplass-gem/src/main/java/org/iplass/gem/command/information/InformationViewCommand.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/top/TopViewDefinitionManagerImpl.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/top/TopViewHandler.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/top/parts/HasNestPartsHandler.java, iplass-gem/src/main/java/org/iplass/mtp/impl/view/top/parts/MetaSeparatorParts.java, iplass-gem/src/main/java/org/iplass/mtp/view/top/TopViewDefinitionManager.java, iplass-gem/src/main/java/org/iplass/mtp/view/top/parts/HasNestParts.java, iplass-gem/src/main/java/org/iplass/mtp/view/top/parts/SeparatorParts.java, iplass-gem/src/main/resources/mtp-gem-messages.properties, iplass-gem/src/main/resources/mtp-gem-messages_en.properties, iplass-gem/src/main/resources/mtp-gem-messages_ja.properties, iplass-gem/src/main/resources/mtp-gem-messages_th.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh_HK.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh_TW.properties
https://github.com/ISID/iPLAss/issues/1176 対応
=> gem、TopView、SeparatorにInformationListを配置すると詳細画面が正常に表示されない

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/UpdateMappedbyReferenceCommand.java
https://github.com/ISID/iPLAss/issues/1179 対応
=> GEM、大量データ用参照セクション、削除処理で既に削除されている場合にNullPointerExceptionが発生する

iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/EQLExecutePane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/MtpListGrid.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/MtpTreeGrid.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/tenant/TenantPluginControllerImpl.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/auth/builtin/BuiltinAuthExplorerMainPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/entityexplorer/crawl/EntityCrawlListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/entityexplorer/datalist/EntityDataListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/entityexplorer/datalist/EntityListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/entityexplorer/defrag/EntityDefragListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/entityexplorer/entityview/gem/GemEntityViewListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/entityexplorer/recycle/RecycleBinListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/langexplorer/LangEditListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/logexplorer/LogExplorerConditionPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/logexplorer/LogExplorerFileListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/metaexplorer/MetaDataTagSelectDialog.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/pack/PackageListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/permissionexplorer/PermissionListGrid.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/permissionexplorer/role/RoleListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/queueexplorer/QueueInfoPane.java, iplass-core/src/main/java/org/iplass/mtp/impl/async/rdb/RdbQueueService.java
https://github.com/ISID/iPLAss/issues/1181 対応
=> AdminConsole、EntityExplorerなどのGridヘッダ上の「Show Filter Row」機能を利用するとシステムエラーが発生する

iplass-core/src/main/java/org/iplass/mtp/impl/metadata/refs/RootMetaDatas.java, iplass-core/src/main/resources/mtp-core-service-config.xml, iplass-gem/src/main/java/org/iplass/mtp/impl/metadata/refs/view/ViewRootMetaDatas.java, iplass-gem/src/main/resources/gem-service-config.xml
- MetaEntityFilter の MetaData 管理を core プロジェクトへ移管
- EntityFilterSerivce の 定義を core プロジェクトの serivce-config.xml へ 移管
=> Core、EntityFilter 整理

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/flat/design.js, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/structure.css, iplass-gem/src/main/sass/flat/structure/_header.scss, iplass-gem/src/main/sass/flat/structure/_main.scss
=> GEM、flatデザインでヘッダー内のコンテンツが折り返されてもデザインが崩れないようにする（3.1）

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/flat/design.js, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/structure.css, iplass-gem/src/main/sass/flat/structure/_header.scss, iplass-gem/src/main/sass/flat/structure/_main.scss
=> GEM、flatデザインでヘッダー内のコンテンツが折り返されてもデザインが崩れないようにする

iplass-gem/src/main/java/org/iplass/gem/command/fulltext/FullTextSearchCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/fulltext/FullTextSearchResult.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/fulltext/search.jsp
=> 全文検索の結果で「検索結果をまとめる」を有効にする

iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/structure.css, iplass-gem/src/main/sass/flat/structure/_headermenu.scss
=> 全文検索の検索領域のレイアウト調整

iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/sass/flat/module/generic/detail/_detail.scss
https://github.com/ISID/iPLAss/issues/1199 対応
=> GEM、詳細画面でのテキストの折り返し改善

iplass-core/src/main/java/org/iplass/mtp/entity/query/Query.java, iplass-core/src/main/java/org/iplass/mtp/entity/query/value/primary/Function.java, iplass-core/src/main/java/org/iplass/mtp/impl/rdb/mysql/MysqlRdbAdaptor.java, iplass-core/src/main/java/org/iplass/mtp/impl/rdb/oracle/OracleRdbAdapter.java, iplass-core/src/main/java/org/iplass/mtp/impl/rdb/postgresql/PostgreSQLRdbAdapter.java, iplass-core/src/main/java/org/iplass/mtp/impl/rdb/sqlserver/SqlServerRdbAdapter.java
- EQL に三角関数を追加
- 追加関数に関連するドックレット修正
=> EQLの関数にsin,cos,acosなどの算術関数を追加

iplass-admin/src/main/java/org/iplass/adminconsole/server/base/service/AdminEntityManager.java, iplass-admin/src/main/java/org/iplass/adminconsole/server/base/service/auditlog/AdminAuditLoggingService.java, iplass-core/src/main/java/org/iplass/mtp/entity/EntityKey.java, iplass-core/src/main/java/org/iplass/mtp/entity/EntityManager.java, iplass-core/src/main/java/org/iplass/mtp/impl/entity/EntityManagerImpl.java, iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntitySearchCsvWriter.java, iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntityWriteOption.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CsvDownloadUploadableWriter.java, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entityport/EntityPortingService.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/CsvUploadService.java, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/command/entity/GetEntityCommand.java, iplass-web/src/main/resources/mtp-web-service-config.xml
https://github.com/ISID/iPLAss/issues/1202 対応
=> CSVダウンロード、多重度複数の参照を含む場合のロード処理を改善（3.1）

iplass-core/src/main/java/org/iplass/mtp/impl/entity/EntityManagerImpl.java
https://github.com/ISID/iPLAss/issues/1202 対応
=> Version管理時のOrderByを変更

iplass-web/src/main/java/org/iplass/mtp/impl/web/WebFrontendService.java, iplass-web/src/main/java/org/iplass/mtp/impl/web/mdc/SessionIdMdcValueResolver.java
=> セッションIDを診断コンテキスト（MDC）にセットする

iplass-gem/src/main/java/org/iplass/gem/command/auth/ResetPasswordCommand.java
=> gem、パスワードリセット時のコマンド動作順序変更

iplass-core/src/main/resources/mtp-core-service-config-mysql-5.7.xml, iplass-core/src/main/resources/mtp-core-service-config-mysql.xml, iplass-core/src/main/resources/mtp-core-service-config-mysql_pseudo_128.xml
https://github.com/ISID/iPLAss/issues/1218 対応
=> MySQL、mtp-core-service-config-mysqlからuseCounterService設定を削除

iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/MySQLTenantRdbManager.java
- パーティションが存在しないテーブルは何もせず処理を継続する
- テーブルにパーティションが存在しない場合に警告メッセージを出力
=> Tools、MySQLテナント作成時のテーブルのパーティション処理の改善

iplass-gem/src/main/java/org/iplass/gem/command/generic/upload/CsvSampleDownloadCommand.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/SearchFormCsvUploadInterrupter.java, iplass-gem/src/main/resources/mtp-gem-messages.properties, iplass-gem/src/main/resources/mtp-gem-messages_en.properties, iplass-gem/src/main/resources/mtp-gem-messages_ja.properties, iplass-gem/src/main/resources/mtp-gem-messages_th.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh_HK.properties, iplass-gem/src/main/resources/mtp-gem-messages_zh_TW.properties
https://github.com/ISID/iPLAss/issues/1233 対応
=> gem、サンプルCSVデータをカスタマイズ可能にする

iplass-core/src/main/java/org/iplass/mtp/impl/rdb/postgresql/PostgreSQLRdbAdapter.java, iplass-core/src/main/java/org/iplass/mtp/impl/rdb/postgresql/function/PostgreSQLSubstrFunctionAdapter.java, iplass-core/src/main/java/org/iplass/mtp/impl/rdb/sqlserver/function/SqlServerSubstrFunctionAdapter.java
- PostgreSQLのSUBSTR関数アダプターを追加
- SqlServerのSUBSTR関数アダプターを修正
=> EQL、SUBSTR 関数の第二引数に負数を指定すると RDB により結果が異なる（3.1）

iplass-core/src/main/java/org/iplass/mtp/impl/cache/store/builtin/SyncServerCacheStoreFactory.java
- インデックスで検索したキャッシュ中のネガティブキャッシュを削除する処理を追加
=> クラスタ構成時にメタデータの更新が反映されないケースがある

iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntityCsvWriter.java, iplass-gem/src/main/java/org/iplass/gem/GemConfigService.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CsvDownloadUploadableWriter.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/upload/CsvSampleDownloadCommand.java
https://github.com/ISID/iPLAss/issues/1249 対応
=> gem、Upload形式のCSVダウンロードで被参照プロパティを出力可能にする

sharedlibs.gradle
- jackson-bom 2.15.2 へバージョンアップ
=> Jacksonライブラリバージョンアップ（3.1）

iplass-web/src/main/java/org/iplass/mtp/impl/web/actionmapping/MetaActionMapping.java, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/MetaWebApi.java
- ワイルドカード指定時にCORS許可メソッドを個別メソッドに展開
- MetaActionMapping の許可メソッドのワイルドカード展開漏れ対応。
- カンマ区切り設定を見直し。
=> RequestRestriction、allowMethodsでワイルドカードが指定された場合のCORS処理の考慮漏れ（3.1）

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/DateRangePropertyEditor.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/NumericRangePropertyEditor.jsp, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/module.css, iplass-gem/src/main/sass/basedesign/module/generic/detail/_detail.scss, iplass-gem/src/main/sass/flat/module/generic/detail/_detail.scss
https://github.com/ISID/iPLAss/issues/1279 対応
=> DateRangePropertyEditor、NumericRangePropertyEditorの調整

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/decimal/DecimalPropertyEditor_Condition.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/number/NumberPropertyEditor_Condition.jsp, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/sass/flat/module/generic/search/_search.scss
https://github.com/ISID/iPLAss/issues/1282 対応
=> gem、flatデザイン、数値系範囲検索の場合の入力領域の幅を調整

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/calendar/ref/calendarFilter.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/completed.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/error.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/search/select.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/about.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/previewDate.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
https://github.com/ISID/iPLAss/issues/1285 対応
=> gem、Windowリサイズ時にサブダイアログのオーバーレイがリサイズされない

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
https://github.com/ISID/iPLAss/issues/1287 対応
=> gem、Windowリサイズ時にサブダイアログのオーバーレイがリサイズされない（3.1）

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/SectionControllerImpl.java
=> 新規登録/編集時の表示可否改善（標準セクション、参照セクション）

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/SectionControllerImpl.java
=> 新規登録/編集時の表示可否改善（標準セクション、参照セクション）（3.1）

iplass-core/src/main/java/org/iplass/mtp/impl/entity/csv/EntityCsvReader.java, iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entityport/EntityPortingService.java, iplass-tools/src/main/resources/mtp-tools-service-config.xml
https://github.com/ISID/iPLAss/issues/1276 対応
=> EntityExplorerにてUserエンティティインポート時、初期パスワードを指定可能にする

iplass-admin/src/main/java/org/iplass/adminconsole/server/metadata/rpc/GemEntityDefinitionOperationController.java
https://github.com/ISID/iPLAss/issues/1299 対応
=> Entity定義生成時に自動で作成するEntityMenuItemに表示名を設定しない

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/SearchConditionSectionControl.java
=> Search_Layoutで検索条件にスペースを置くと最後尾に配置される（3.1）

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/SearchConditionSectionControl.java
=> Search_Layoutで検索条件にスペースを置くと最後尾に配置される

iplass-web/libs.gradle, sharedlibs.gradle
- JasperReports 6.20.6 へバージョンアップ
- OpenPDF 1.3.33 を明示的に指定
=> JasperReports ライブラリバージョンアップ

iplass-gem/src/main/java/org/iplass/gem/command/Constants.java, iplass-gem/src/main/java/org/iplass/gem/command/MetaDataRefs.java, iplass-gem/src/main/java/org/iplass/gem/command/auth/UpdatePasswordCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/auth/ViewUserMaintenanceCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/NestTableCommandContext.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Table.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/header.jsp
=> GEM、ユーザー情報変更でネストテーブルを使用するとエラー(3.1)

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/flat/design.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/horizontal/design.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/vertical/design.js
=> gem、CHECKBOXタイプの連動プロパティの表示がおかしい、選択解除ができない

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/flat/design.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/horizontal/design.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/vertical/design.js
=> gem、CHECKBOXタイプの連動プロパティの表示がおかしい、選択解除ができない(3.1)

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Condition.jsp
https://github.com/ISID/iPLAss/issues/1355 対応
=> gem、検索条件でのReferencePropertyEditorの参照コンボにて、上位層しか選択していない場合に、復元されない（3.1）

iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/lucene/LuceneFulltextSearchService.java
全文検索、index生成処理完了後にINFOでログ出力するように修正する。
=> 全文検索、index生成処理完了後にINFOでログ出力する

iplass-gem/src/main/java/org/iplass/gem/command/calendar/CalendarData.java, iplass-gem/src/main/java/org/iplass/gem/command/calendar/GetCalendarCommand.java
=> gem、Calendar、Entity Colorの設定がカレンダーに反映されない

iplass-gem/src/main/java/org/iplass/gem/command/generic/refcombo/ReferenceComboCommand.java
https://github.com/ISID/iPLAss/issues/1371 対応
=> gem、参照コンボで上位設定で検索条件を指定している場合にエラーになる

iplass-gem/src/main/java/org/iplass/gem/command/generic/refcombo/ReferenceComboCommand.java
https://github.com/ISID/iPLAss/issues/1373 対応
=> gem、参照コンボで上位設定で検索条件を指定している場合にエラーになる（3.1）

iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/MtpBatchResourceDisposer.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/AsyncTaskCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/AuthProviderCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/InvalidMetaDataCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/RbCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/RdbCacheCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/TempLobCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/TempUserCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/config/ServiceConfigViewer.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EQLExecutor.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityDeleteAll.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityImport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityJavaMappingClassCreator.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityUpdateAll.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityViewDDLCreator.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/fulltextsearch/EntityDataCrawler.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/lob/LobStoreMigrator.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataImport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataNameListExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataPatch.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageImport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/partition/MySQLPartitionBatch.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/partition/PostgreSQLPartitionBatch.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/storagespace/ObjStoreDDLGenerateBatch.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/storagespace/StorageSpaceCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/storagespace/StorageSpaceMigration.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/tenant/TenantBatch.java
=> バッチツール、処理終了時に全Serviceを破棄する処理を入れる

iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/MtpBatchResourceDisposer.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/AsyncTaskCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/AuthProviderCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/InvalidMetaDataCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/RbCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/RdbCacheCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/TempLobCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/cleaner/TempUserCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/config/ServiceConfigViewer.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EQLExecutor.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityDeleteAll.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityImport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityJavaMappingClassCreator.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityUpdateAll.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EntityViewDDLCreator.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/fulltextsearch/EntityDataCrawler.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/lob/LobStoreMigrator.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataImport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataNameListExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/metadata/MetaDataPatch.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageExport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageImport.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/partition/MySQLPartitionBatch.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/partition/PostgreSQLPartitionBatch.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/storagespace/ObjStoreDDLGenerateBatch.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/storagespace/StorageSpaceCleaner.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/storagespace/StorageSpaceMigration.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/tenant/TenantBatch.java
=> バッチツール、処理終了時に全Serviceを破棄する処理を入れる（3.1）

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
https://github.com/ISID/iPLAss/issues/1382 対応
=> 選択解除時の考慮漏れ対応

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java
GEM、大量データ用参照セクションのソートロジックの改善する。
=> GEM、大量データ用参照セクションのソートロジックの改善（3.1）

gradle.properties
=> MANIFESTファイルの会社名変更

iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entityport/EntityPortingService.java, iplass-tools/src/main/resources/mtp-tools-messages.properties, iplass-tools/src/main/resources/mtp-tools-messages_en.properties, iplass-tools/src/main/resources/mtp-tools-messages_ja.properties, iplass-web/src/main/java/org/iplass/mtp/impl/csv/EntityCsvImportOption.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/EntityCsvImportResult.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/EntityCsvImportRuntimeException.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/EntityCsvImportService.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/EntityCsvImportTask.java, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/EntityWebApiService.java, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/command/entity/CreateEntityCommand.java, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/command/entity/UpdateEntityCommand.java, iplass-web/src/main/resources/mtp-web-messages.properties, iplass-web/src/main/resources/mtp-web-messages_en.properties, iplass-web/src/main/resources/mtp-web-messages_ja.properties, iplass-web/src/main/resources/mtp-web-messages_th.properties, iplass-web/src/main/resources/mtp-web-messages_zh.properties, iplass-web/src/main/resources/mtp-web-messages_zh_HK.properties, iplass-web/src/main/resources/mtp-web-messages_zh_TW.properties, iplass-web/src/main/resources/mtp-web-service-config.xml
=> EntityCRUD API、制御オプションを指定可能に（3.1）

iplass-tools/src/main/java/org/iplass/mtp/impl/tools/entityport/EntityPortingService.java, iplass-tools/src/main/resources/mtp-tools-messages.properties, iplass-tools/src/main/resources/mtp-tools-messages_en.properties, iplass-tools/src/main/resources/mtp-tools-messages_ja.properties, iplass-tools/src/main/resources/mtp-tools-service-config.xml, iplass-web/src/main/java/org/iplass/mtp/impl/csv/EntityCsvImportOption.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/EntityCsvImportResult.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/EntityCsvImportRuntimeException.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/EntityCsvImportService.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/EntityCsvImportTask.java, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/EntityWebApiService.java, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/command/entity/CreateEntityCommand.java, iplass-web/src/main/java/org/iplass/mtp/impl/webapi/command/entity/UpdateEntityCommand.java, iplass-web/src/main/resources/mtp-web-messages.properties, iplass-web/src/main/resources/mtp-web-messages_en.properties, iplass-web/src/main/resources/mtp-web-messages_ja.properties, iplass-web/src/main/resources/mtp-web-messages_th.properties, iplass-web/src/main/resources/mtp-web-messages_zh.properties, iplass-web/src/main/resources/mtp-web-messages_zh_HK.properties, iplass-web/src/main/resources/mtp-web-messages_zh_TW.properties, iplass-web/src/main/resources/mtp-web-service-config.xml
=> EntityCRUD API、制御オプションを指定可能に

iplass-core/src/main/java/org/iplass/mtp/impl/entity/EntityManagerImpl.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/RegistrationCommandBase.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/RegistrationCommandContext.java
https://github.com/dentsusoken/iPLAss/issues/1415 対応
=> バージョン管理されているEntityのload互換対応

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/view.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_View.jsp
https://github.com/dentsusoken/iPLAss/issues/1425 対応
=> gem、ReferencePropertyEditorで参照リンクで編集を許可している場合にダイアログの保存時にエラーが発生する

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/ref/view.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_View.jsp
https://github.com/dentsusoken/iPLAss/issues/1427 対応
=> gem、ReferencePropertyEditorで参照リンクで編集を許可している場合にダイアログの保存時にエラーが発生する（3.1）

iplass-core/src/main/java/org/iplass/mtp/spi/ServiceRegistry.java, iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/MtpBatchResourceDisposer.java
=> Service取得時に利用側でインスタンス生成を行うかを指定できる機能を追加

sharedlibs.gradle
- compress 1.26.0
- io 2.15.1
- lang3 3.14.0
=> Apache Commons ライブラリをバージョンアップする

sharedlibs.gradle
- core, parsers を 1.28.5 にバージョンアップ
=> Apache Tika ライブラリバージョンアップ

iplass-core/libs.gradle, sharedlibs.gradle
- metadata-extractor ライブラリの依存関係を追加
=> 全文検索、pptxバイナリファイルのクロールに失敗する（3.1）

iplass-core/libs.gradle, sharedlibs.gradle
- metadata-extractor ライブラリの依存関係を追加
=> 全文検索、pptxバイナリファイルのクロールに失敗する

iplass-gem/src/main/java/org/iplass/gem/GemConfigService.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/search/DetailSearchContext.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchConditionSection.jsp, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/i18n/gem-locale-en.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/i18n/gem-locale-ja.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/i18n/gem-locale-th.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/i18n/gem-locale-zh-CN.js, iplass-gem/src/main/resources/META-INF/resources/scripts/gem/i18n/gem-locale-zh-TW.js, iplass-gem/src/main/resources/gem-service-config.xml
GEM、詳細検索における検索項目数の上限をGemConfigServiceで指定可能に修正する。
=> GEM、詳細検索における検索項目数の上限をGemConfigServiceで指定可能に

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/BulkDropLayout.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/DetailDropLayout.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/EntityViewItemDropLayout.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/DefaultSectionControl.java
=> GEM、BulkLayoutで標準セクションにプロパティを配置すると詳細画面用の項目が表示される

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/BulkDropLayout.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/DetailDropLayout.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/EntityViewItemDropLayout.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/layout/item/element/section/DefaultSectionControl.java
=> GEM、BulkLayoutで標準セクションにプロパティを配置すると詳細画面用の項目が表示される（3.1）

iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/AbstractFulltextSearchService.java, iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/parser/AbstractBinaryReferenceParser.java, iplass-core/src/main/resources/mtp-core-service-config.xml
- バイナリファイルパース時に実行時例外の発生時、特定の例外であれば処理継続する
- 継続する例外クラスの設定例記載
=> 全文検索、バイナリパース時に想定外の例外が発生しても処理継続する

iplass-core/src/main/java/org/iplass/mtp/impl/cluster/channel/jgroups/JGroupsMessageChannel.java, sharedlibs.gradle
- jgroups 4.2.16.Final to 5.3.6.Final
- コンパイルエラー箇所の修正
=> jgroups 5 系へバージョンアップ

iplass-admin/src/main/resources/org/iplass/adminconsole/AdminConsole.gwt.xml, iplass-admin/src/main/resources/org/iplass/adminconsole/AdminConsoleBase.gwt.xml, iplass-admin/src/main/resources/org/iplass/adminconsole/AdminConsoleRpcBlacklist.gwt.xml, iplass-admin/src/main/resources/org/iplass/gwt/ace/GwtAce.gwt.xml
- gwt 実行時エラーが発生することを抑制するため、rpc.blacklist を追加
- gwt.xml のバージョン情報を更新
=> JakartaEE10/Tomcat10.1対応 gwt client 実行時エラー対応

iplass-core/src/main/java/org/iplass/mtp/impl/webhook/DefaultWebhookResponseHandler.java
https://github.com/dentsusoken/iPLAss/issues/1480 対応
=> Webhook、DefaultWebhookResponseHandlerのステータスコードの判定がおかしい

iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/module.css, iplass-gem/src/main/sass/basedesign/module/generic/detail/_detail.scss, iplass-gem/src/main/sass/flat/module/generic/detail/_detail.scss
fix #1485 #1503
1485：新旧デザイン、編集画面
1503：旧デザイン、詳細画面
=> GEM、詳細・編集画面の折り返し設定改善（4.0）

iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/module.css, iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/module.css, iplass-gem/src/main/sass/basedesign/module/generic/detail/_detail.scss, iplass-gem/src/main/sass/flat/module/generic/detail/_detail.scss
fixes #1498 #1502
1498：新旧デザイン、編集画面
1502 ：旧デザイン、詳細画面
=> GEM、詳細・編集画面の折り返し設定改善

sharedlibs.gradle
- 誤って削除した Jakarta EL Impl の依存関係を復元
=> Infinispan、JDK21、JakartaEE10対応 依存関係修正

iplass-test/build.gradle, iplass-test/src/demo/resources/testsample/test-sample-metadata.xml, iplass-test/src/demo/resources/testsample/test-sample-service-config.xml
=> テスト、demo 設定見直し

iplass-core/libs.gradle, iplass-gem/libs.gradle, iplass-test/libs.gradle, iplass-web/libs.gradle, sharedlibs.gradle
- groovy ライブラリバージョンアップ ( 3.0.21 -> 4.0.21 )
=> groovy 4系へバージョンアップ

sharedlibs.gradle
ライブラリバージョンアップ
- commons-pool2 2.11.1 -> 2.12.0
- REDIS動作確認
特になし
=> commons-pool2、バージョンアップ（4.0）

sharedlibs.gradle
- commons-codec:commons-codec 1.15 -> 1.17.0
- 汎用エンティティ操作（登録、更新、参照、削除）
- AdminConsole エンティティ作成・削除
特になし
=> commons-codec、バージョンアップ（4.0）

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/RegistrationCommandBase.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/RegistrationInterrupterHandler.java, iplass-gem/src/main/java/org/iplass/mtp/view/generic/RegistrationInterrupter.java
RegistrationInterrupterのインターフェースを変更する。
- beforeRegist -> beforeRegister
- afterRegist -> afterRegister
既存のインターフェースはDeprecatedとして、新規インターフェースから呼び出す。
close #1534
=> GEM、RegistrationInterrupterのインターフェース変更

iplass-web/src/main/java/org/iplass/mtp/csv/CsvUploadInterrupter.java, iplass-web/src/main/java/org/iplass/mtp/impl/csv/CsvUploadService.java
CsvUploadInterrupterのインターフェースを変更する。
- beforeRegist -> beforeRegister
- afterRegist -> afterRegister
既存のインターフェースはDeprecatedとして、新規インターフェースから呼び出す。
close #1536
=> GEM、SearchFormCsvUploadInterrupterのインターフェース変更

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
追加、削除、ページ移動など、データ検索後にコンテンツの高さを調整する。
close #1544
=> GEM、大量データSectionでデータを追加していくとフッタの文言とコンテンツが重なってしまう

iplass-web/libs.gradle
- jxls に古い logback-core が含まれていたので、依存関係整理
- UT実行
特になし
=> ログ関連ライブラリ、バージョンアップ（4.0） jxls 依存関係整理

sharedlibs.gradle
- com.github.ben-manes.caffeine:caffeine 2.9.3 -> 3.1.8
- GEM操作（エンティティ登録、更新、表示、削除）
- 特になし
=> caffeine、バージョンアップ（4.0）

sharedlibs.gradle
- io.lettuce:lettuce-core 6.2.5.RELEASE -> 6.3.2.RELEASE
- キャッシュ動作確認
特になし
=> lettuce、バージョンアップ（4.0）

sharedlibs.gradle
- com.ibm.icu:icu4j 69.1 -> 75.1
- Entity プロパティに ICU Transliterator を設定しデータ登録
特になし
=> ICU4J、バージョンアップ（4.0）

iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/ScriptEditorDialogMode.java, iplass-admin/src/main/java/org/iplass/gwt/ace/client/EditorMode.java, iplass-admin/src/main/resources/META-INF/resources/jsp/admin/main.jsp, sharedlibs.gradle
close #1586 
Admin ConsoleでのAceエディタの動作を確認
=> AdminConsole: Aceエディタのバージョンアップ

iplass-core/libs.gradle, iplass-core/src/main/java/org/iplass/mtp/impl/cluster/channel/http/HttpMessageChannel.java, iplass-core/src/main/java/org/iplass/mtp/impl/http/HttpClientBuilderFactory.java, iplass-core/src/main/java/org/iplass/mtp/impl/http/HttpClientConfig.java, iplass-core/src/main/java/org/iplass/mtp/impl/http/SimpleHttpInvoker.java, iplass-core/src/main/java/org/iplass/mtp/impl/pushnotification/fcm/FCMPushNotificationService.java, iplass-core/src/main/java/org/iplass/mtp/impl/webhook/WebhookServiceImpl.java, iplass-web/libs.gradle, iplass-web/src/main/java/org/iplass/mtp/impl/auth/authenticate/oidc/OPEndpoint.java, iplass-web/src/main/java/org/iplass/mtp/impl/auth/authenticate/oidc/OpenIdConnectService.java, iplass-web/src/main/java/org/iplass/mtp/impl/auth/authenticate/oidc/jwks/RemoteJwks.java, iplass-web/src/main/java/org/iplass/mtp/impl/auth/oauth/token/remote/RemoteOAuthAccessTokenStore.java, sharedlibs.gradle
- org.apache.httpcomponents:httpclien4.5.13 -> org.apache.httpcomponents.client5:httpclient5 5.3.1
- 追加： org.apache.httpcomponents.core5:httpcore5 5.2.5
- 追加： org.apache.httpcomponents.core5:httpcore5-h2 5.2.5
- 削除： org.apache.httpcomponents:httpmime
- httpcomponents バージョンアップによるクラスパッケージ変更
- deprecated メソッド部のロジック修正
- HttpClientConfig を利用したアプリ動作確認（ Cluster Http Channel 確認、Webhook 確認 ）
- OIDC RP 動作確認
- 認証サーバー確認
- アプリとして動作可能なところは動かしてみています。
=> HttpComponents、バージョンアップ（4.0）

iplass-core/src/main/java/org/iplass/mtp/impl/cluster/channel/http/HttpMessageChannel.java, iplass-core/src/main/java/org/iplass/mtp/impl/http/SimpleHttpInvoker.java, iplass-core/src/main/java/org/iplass/mtp/impl/webhook/WebhookServiceImpl.java
- WebhookServiceImpl の Content-Encoding 指定誤り
- 変数名の見直し(contentEncoding -> contentCharset)
- Webhook POST 形式実行
特になし
=> HttpComponents、バージョンアップ（4.0）  fixbugs

iplass-gem/src/main/java/org/iplass/gem/command/calendar/CalendarEntityData.java
fix #1608 
バグ再現手順を実行し、NullPointerが発生しないことを確認。
=> GEM: Calendar定義が既に存在していた場合のNull考慮漏れ対応

iplass-gem/libs.gradle, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/coreResource.inc.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/datepickerResource.inc.jsp, sharedlibs.gradle
GEMモジュールで利用しているjQuery、jQuery UIのライブラリバージョンアップ。
| library | from | to |
| --- | --- | --- |
| org.webjars:jquery | 3.5.1 | 3.7.1 |
| org.webjars.bowergithub.jquery:jquery-ui   -> org.webjars.npm:jquery-ui | 1.13.2 | 1.13.3 |
fixes #1636
=> jQuery、jQuery UIのバージョンアップ（3.2）

iplass-admin/src/main/java/org/iplass/adminconsole/server/tools/rpc/logexplorer/LogExplorerServiceImpl.java
AdminConsoleのLogExplorerにて、logHome設定が複数ある場合は、PathにlogHomeも表示する。
異なるlogHome配下に同一のログが存在した場合に、判断ができないため。
closes #1663
=> LogHomeが複数指定されている時の表示改善

iplass-admin/src/main/java/org/iplass/adminconsole/server/tools/rpc/logexplorer/LogExplorerServiceImpl.java
AdminConsoleのLogExplorerにて、logHome設定が複数ある場合は、PathにlogHomeも表示する。
異なるlogHome配下に同一のログが存在した場合に、判断ができないため。
closes #1671
=> LogHomeを複数指定時の表示改善

sharedlibs.gradle
- io.lettuce:lettuce-core 6.3.2.RELEASE -> 6.5.2.RELEASE (2025-01-17 時点最新版）
- redis を利用したキャッシュ利用
特にありません
=> lettuceバージョンアップ

iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css
GEM: フラットデザイン時のチェックボックスの形状の統一性をとる対応
GEM: フラットデザイン時のチェックボックスの形状の統一性をとるhttps://github.com/dentsusoken/iPLAss/issues/1661
検索条件でプロパティエディタでチェックボックスを指定した場合
詳細画面チェックボックスをエディタする場合
=> GEM: フラットデザイン時のチェックボックスの形状の統一性をとる対応

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java
fixes #1681
画面定義でのソート設定時のEQL確認
画面からのリクエスト時に画面定義にない項目のソート指定時の動作確認
=> 大量データ参照セクションのソート設定時の動き改善

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java
fixes #1691
画面定義でのソート設定時のEQL確認
画面からのリクエスト時に画面定義にない項目のソート指定時の動作確認
=> 大量データ参照セクションのソート設定時の動き改善（3.2）

iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/BulkCommandContext.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/MultiBulkCommandContext.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java
=> Entity更新時の参照先のロード処理のパフォーマンス改善 #1701

gradle.properties
4.0.5 のリリースを再実行するため、リリース時に発生したコミットを取り消し。
特にありません。
特にありません。
=> 4.0.5 release の取り消し

iplass-core/src/main/java/org/iplass/mtp/util/DateUtil.java
- ZonedDateTime を扱うことが可能なメソッドを追加
- 追加した機能を利用した機能のテスト
特になし
=> DateUtil: 機能追加

iplass-core/src/main/java/org/iplass/mtp/impl/util/ClassUtil.java
- ClassUtil クラス追加
- クラスを利用した機能の動作確認実施
特になし
=> Class ユーティリティ追加

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/EventListenerListGrid.java
- スペルミスを修正
- Script, JavaClass, SendNotification でそれぞれスペルが修正されていることを確認。
Script
JavaClass
SendNotification
特にありません
=> AdminConsole: エンティティイベントリスナーのオプション説明のスペルミス（3.2）

iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/ScriptEditorDialogConstants.java
ファイルダウンロード時にサポートされるタイプが拡張されたため、定数の中でCSVを含む部分をFILEに変更する必要があります。
closes #1714
=> GEM: すべてのファイルタイプに対応可能のために、定数名を修正する。

iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/MultiBulkCommandContext.java
#1706 と同様の修正をBulkViewによる一括更新処理に適用する。
fixes #1738
#1706 と同様。
=> GEM: 検索結果からBulkViewを使い一括更新する場合に、Entityのソート順で更新されるよう修正

iplass-gem/src/main/java/org/iplass/gem/command/Constants.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailViewCommand.java, iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/UpdateCommand.java, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/edit.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/view.jsp, iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/VersionSection.jsp
#1688 の修正を3.2に反映する。
closes #1727
#1688 と同様。
=> GEM: 詳細画面から特定バージョンに遷移した場合でもEntityを更新できるよう修正（3.2）

iplass-core/src/main/java/org/iplass/mtp/impl/metadata/MetaDataRepository.java
- 無効なメタデータを検索する際は、メタデータIDで集約し返却する。
- 同一メタデータパスで、作成・削除を繰り返し、Invalid MetaData Cleaner を実行。削除したメタデータがすべて消えていることを確認。
- 4.0 のコードをバックポートしています。
=> 無効なメタデータの削除処理（Invalid MetaData Cleaner）にて、同一パス名で定義したメタデータIDの異なる無効メタデータが存在する場合正しく削除処理できない（3.2）

iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/ScriptEditorDialogMode.java, iplass-admin/src/main/java/org/iplass/gwt/ace/client/EditorMode.java, iplass-admin/src/main/resources/META-INF/resources/jsp/admin/main.jsp
- AceエディタHighlight用ファイルを追加
- 追加したファイルのエディターモードを追加
- AdminConsole AceエディタにJSON,YAML Highlightが利用できることを確認
JSON, YAML が選択可能
JSON Highlight
YAML Highlight
=> AdminConsole: Aceエディタ Highlight に JSON, YAML を追加

iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/ScriptEditorDialog.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/ScriptEditorDialogHandler.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/ScriptEditorDialogSetting.java
- ダイアログで設定可能な項目の取得機能を追加
- ScriptEditorDialogHandler に追加したメソッドで設定情報が取得できることの確認
* EditorPane で管理している Aceエディタから設定情報を取得しようとも考えましたが、以下の点がネックと考え最上位で設定を管理するようにしました。
* native コードを書く必要が出てくる（Javaコードのようにコンパイルできない）。
* 影響範囲が大きくなる
=> AdminConsole: Aceエディタ編集完了時にHighlight設定の取得機能を追加

iplass-web/src/main/java/org/iplass/mtp/impl/fileport/EntityFileUploadOption.java
GEM: uploadを非同期処理の場合、EntityFileUploadOptionエラー修正
closes #1782 
upload機能を非同期処理に設定する
非同期処理が正常に動作する。
=> GEM: uploadを非同期処理の場合、EntityFileUploadOptionエラー修正

iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/ScriptEditorDialogConstants.java
#1791 と同様の対応を3.2にbackportする。
closes #1793 
#1791 と同様。
=> 不要な定数を削除（3.2）

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
fixes #1789
詳細画面からリファレンス編集時のCallback関数をカスタマイズできるようにする
=> GEM:詳細画面からリファレンス編集時のCallback関数をカスタマイズできるようにする（3.2）

sharedlibs.gradle
- org.apache.commons:commons-lang3 3.14.0 -> 3.18.0
- 標準Entityの登録・参照・更新・削除
=> Commons Lang 3.18.0 バージョンアップ

iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/ScriptEditorDialogConstants.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/property/ValidationListGridRecord.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/property/ValidationListPane.java, iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/property/validation/ValidationEditDialog.java, iplass-admin/src/main/java/org/iplass/adminconsole/server/tools/rpc/entityexplorer/EntityPropertyCsvWriter.java, iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_en.js, iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_ja.js, iplass-core/src/main/java/org/iplass/mtp/entity/definition/ValidationDefinition.java, iplass-core/src/main/java/org/iplass/mtp/impl/validation/MetaValidation.java, iplass-core/src/main/java/org/iplass/mtp/impl/validation/MetaValidationBinarySize.java, iplass-core/src/main/java/org/iplass/mtp/impl/validation/MetaValidationBinaryType.java, iplass-core/src/main/java/org/iplass/mtp/impl/validation/MetaValidationExists.java, iplass-core/src/main/java/org/iplass/mtp/impl/validation/MetaValidationJavaClass.java, iplass-core/src/main/java/org/iplass/mtp/impl/validation/MetaValidationLength.java, iplass-core/src/main/java/org/iplass/mtp/impl/validation/MetaValidationNotNull.java, iplass-core/src/main/java/org/iplass/mtp/impl/validation/MetaValidationRange.java, iplass-core/src/main/java/org/iplass/mtp/impl/validation/MetaValidationRegex.java, iplass-core/src/main/java/org/iplass/mtp/impl/validation/MetaValidationScripting.java, iplass-core/src/main/java/org/iplass/mtp/impl/validation/ValidationHandler.java
backport of https://github.com/dentsusoken/iPLAss/issues/1768
closes #1806
=> Entity: バリデーションの実行条件を設定可能にする（3.2）

sharedlibs.gradle
- commons-codec:commons-codec 1.17.0 -> 1.19.0
- アプリケーション動作確認
- commons-codec のリリースノートで、breaking change が無いことの確認
とくにありません
=> Commons Codec 1.19.0 バージョンアップ

sharedlibs.gradle
- org.apache.poi:poi 5.3.0 -> 5.4.1
- org.apache.poi:poi-scratchpad 5.3.0 -> 5.4.1
- org.apache.poi:poi-ooxml 5.3.0 -> 5.4.1
- アプリケーション動作確認（帳票出力、クロール）
- poi のリリースノートで、breaking change が無いことの確認
特にありません
=> Apache POI 5.4.1 バージョンアップ

iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/parser/BinaryPDFParser.java
- XFAパース対象外にする設定を追加
- 全文検索PDFパース処理確認
特にありません
=> 全文検索: BinaryPDFParserでXFAはパースしないようにする

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/string/StringPropertyEditor_Edit.jsp
StringPropertyEditorで「入力パターン」と「最大文字数」を同時に設定すると maxlength 属性内に pattern が含まれてしまう不具合の修正
fixes #1832
=> GEM: プロパティエディタで「入力パターン」と「最大文字数」を同時に設定すると maxlength 属性内に pattern が含まれてしまう

iplass-redis/libs.gradle, sharedlibs.gradle
- io.lettuce:lettuce-core 6.7.1.RELEASE -> 6.8.1.RELEASE
- 推移依存する netty ライブラリのバージョンを 4.1.126.Final に固定
- redis キャッシュを利用テスト
- ライブラリバージョンアップのみです
=> lettuce 6.8.1.RELEASE バージョンアップ
