iplass-tools-batch/src/main/bat/start_package_import.bat
iplass-tools-batch/src/main/conf/pack-imp-config.properties
iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageExport.java
iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageImport.java
iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/pack/PackageImportParameter.java
iplass-tools-batch/src/main/resources/mtp-tools-batch-messages.properties
iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_en.properties
iplass-tools-batch/src/main/resources/mtp-tools-batch-messages_ja.properties
iplass-tools-batch/src/main/sh/start_package_import.sh

Packageバッチ、サイレント実行モードを追加 #3。
現状、ウィザード形式でしか実行できないが、バックアップなどの利用用途のために
サイレントモードでの実行を可能にする。
入力パラメータについては、パラメータ数が多いため、propertyファイルとして別途指定する方式で提供。

Packageバッチ、サイレント実行モードを追加

---

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/flat/design.js

#68 対応。
フラットスキンのチェックボックスの表示偽装処理の対象からjqGridの選択チェックボックスを除外する。

フラットスキン、大量データ参照セクションで削除ボタンが効かない

---

iplass-admin/build.gradle
iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/webapi/WebApiAttributePane.java
iplass-web/src/main/java/org/iplass/mtp/command/annotation/webapi/WebApi.java
iplass-web/src/main/java/org/iplass/mtp/impl/webapi/MetaWebApi.java
iplass-web/src/main/java/org/iplass/mtp/impl/webapi/MetaWebApiFactory.java
iplass-web/src/main/java/org/iplass/mtp/impl/webapi/rest/RestCommandInvoker.java
iplass-web/src/main/java/org/iplass/mtp/webapi/definition/CacheControlType.java
iplass-web/src/main/java/org/iplass/mtp/webapi/definition/WebApiDefinition.java

WebAPI定義にてCache-Controlを設定可能にする。
Action定義と同様な形で。
https://github.com/ISID/iPLAss/issues/93 対応。

WebAPI定義にてCache-Controlを設定可能にする #93

---

iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/HasEntityProperty.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/common/MetaAutocompletionProperty.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/MetaElement.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/property/MetaPropertyColumn.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/property/MetaPropertyItem.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/property/MetaPropertyLayout.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/property/validation/MetaPropertyValidationCondition.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaDefaultSection.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaMassReferenceSection.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaReferenceSection.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaSearchConditionSection.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaSearchResultSection.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaSortSetting.java

#110 対応。
EntityViewの編集画面を表示する際に、MetaDataからDefinitionに変換を行うが、
このタイミングで無効なプロパティを参照しているエレメントは除外する。

プロパティを削除した後に画面定義を保存できなくなる

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchResultSection.jsp

gem、Rererenceの多重度が数値指定されている場合、検索ダイアログで全選択チェックした際のメッセージが正しく表示されない

---

iplass-admin/src/main/java/org/iplass/adminconsole/server/base/rpc/tenant/TenantServiceImpl.java
iplass-admin/src/main/java/org/iplass/adminconsole/server/metadata/rpc/EntityDefinitionOperationController.java
iplass-admin/src/main/java/org/iplass/adminconsole/server/metadata/rpc/GemEntityDefinitionOperationController.java
iplass-admin/src/main/java/org/iplass/adminconsole/server/metadata/rpc/MetaDataServiceImpl.java
iplass-admin/src/main/java/org/iplass/adminconsole/server/metadata/rpc/refrect/RefrectionServiceImpl.java
iplass-admin/src/main/java/org/iplass/adminconsole/server/tools/rpc/entityexplorer/EntityConfigDownloadServiceImpl.java
iplass-admin/src/main/java/org/iplass/adminconsole/server/tools/rpc/entityexplorer/EntityExplorerServiceImpl.java

フィールドに定義された画面系クラス（Manager、Service）を利用箇所で宣言する形に変更
Entityの表示名更新時、メニューの更新処理をControllerに移動

AdminCnosoleのserviceクラスのリファクタリング

---

iplass-web/src/main/resources/mtp-web-service-config.xml

マジックバイトチェック：Firefox(Windows版)でCSVファイルアップロードが失敗する

---

iplass-gem/src/main/java/org/iplass/mtp/view/generic/element/section/SearchResultSection.java

https://github.com/ISID/iPLAss/issues/1123 対応

gem、検索結果の表示行数の最大値制御を削除

---

iplass-core/src/main/java/org/iplass/mtp/impl/rdb/connection/AbstractConnectionFactory.java
iplass-core/src/main/java/org/iplass/mtp/impl/rdb/connection/ReplicationAwareDataSourceConnectionFactory.java

- ReadOnly の場合にコネクションを作成するのは、必要な場合に限定する
- ReadOnly の場合にコネクションを作成するフラグは ServiceConfig の設定で変更可能とする

ReadOnlyトランザクションの挙動の改善

---

iplass-core/src/main/java/org/iplass/mtp/impl/lob/lobstore/rdb/RdbLobData.java

PostgreSQL利用時、LongTextに大きなサイズの文字列を設定し更新するとSQL例外が発生する（3.1）

---

iplass-core/src/main/java/org/iplass/mtp/impl/rdb/postgresql/PostgreSQLRdbAdapter.java
iplass-core/src/main/java/org/iplass/mtp/impl/rdb/postgresql/function/PostgreSQLSubstrFunctionAdapter.java
iplass-core/src/main/java/org/iplass/mtp/impl/rdb/sqlserver/function/SqlServerSubstrFunctionAdapter.java

- PostgreSQLのSUBSTR関数アダプターを追加
- SqlServerのSUBSTR関数アダプターを修正

EQL、SUBSTR 関数の第二引数に負数を指定すると RDB により結果が異なる

---

iplass-core/src/main/java/org/iplass/mtp/impl/cache/store/builtin/SyncServerCacheStoreFactory.java

- インデックスで検索したキャッシュ中のネガティブキャッシュを削除する処理を追加

クラスタ構成時にメタデータの更新が反映されないケースがある（3.1）

---

iplass-web/src/main/java/org/iplass/mtp/impl/web/actionmapping/MetaActionMapping.java
iplass-web/src/main/java/org/iplass/mtp/impl/webapi/MetaWebApi.java

- ワイルドカード指定時にCORS許可メソッドを個別メソッドに展開
- MetaActionMapping の許可メソッドのワイルドカード展開漏れ対応。
- カンマ区切り設定を見直し。

RequestRestriction、allowMethodsでワイルドカードが指定された場合のCORS処理の考慮漏れ

---

iplass-web/src/main/java/org/iplass/mtp/impl/webapi/WebApiService.java
iplass-web/src/main/java/org/iplass/mtp/impl/webapi/command/binary/BinaryCommand.java
iplass-web/src/main/resources/mtp-web-service-config.xml

- WebApiService にバイナリアップロード受け入れ可能なMIME Typeパターンを追加
- WebAPI ファイルアップロード時にMIME Typeを判別し、受け入れ可否を判定する

WebAPI、アップロード可能なmimeTypeを指定可能にする

---

iplass-gem/src/main/java/org/iplass/gem/GemConfigService.java
iplass-gem/src/main/java/org/iplass/gem/command/binary/UploadCommand.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/FormViewRuntime.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/FormViewRuntimeUtil.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaBinaryPropertyEditor.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaNestProperty.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/HasSectionPropertyRuntimeMap.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaDefaultSection.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/MetaReferenceSection.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/SectionNestPropertyRuntime.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/SectionPropertyRuntime.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/SectionPropertyRuntimeBuilder.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/element/section/SectionPropertyRuntimeImpl.java
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp
iplass-gem/src/main/resources/mtp-gem-messages.properties
iplass-gem/src/main/resources/mtp-gem-messages_en.properties
iplass-gem/src/main/resources/mtp-gem-messages_ja.properties
iplass-gem/src/main/resources/mtp-gem-messages_th.properties
iplass-gem/src/main/resources/mtp-gem-messages_zh.properties
iplass-gem/src/main/resources/mtp-gem-messages_zh_HK.properties
iplass-gem/src/main/resources/mtp-gem-messages_zh_TW.properties

- GemConfigService で保持するパターン情報をPatternインスタンスに変更
- 更新実行時にバイナリファイルタイプを検査
- プロパティエディタの検査パターンインスタンスを事前コンパイル
- FormViewRuntime 保持情報を整理
- プロパティのmultiple対応
- ネストプロパティ対応

gem、バイナリプロパティ更新時のmimeTypeチェックの改善

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/SearchConditionSection.jsp

詳細：ミリ秒の補完が「000」で固定になっているが、「以下」と「より大きい」の場合、ミリ秒を「999」で補完するように修正します。 
担当者：rikouki

GEM、詳細検索、DateTime型プロパティが検索項目に指定された場合のミリ秒補完を改善する

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/ckeditorResource.inc.jsp
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/plugin/ckeditor/mtpconfig.js
iplass-gem/src/main/resources/META-INF/resources/webjars/ckeditor/4.22.1/full/plugins/autogrow/plugin.js
sharedlibs.gradle

- ライブラリバージョンアップ（4.14.0 -> 4.22.1）
- exportpdf プラグイン削除（Error code: exportpdf-no-token-url の抑制）

CKEditorバージョンアップ

---

iplass-core/src/main/resources/schema/sql/ddl/sqlserver_partition/partition.sql
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/TenantToolService.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/DefaultTenantRdbManager.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/MySQLTenantRdbManager.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/OracleTenantRdbManager.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/PostgreSQLTenantRdbManager.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/SqlServerTenantRdbManager.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/TenantRdbConstants.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/TenantRdbManagerFactory.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/TenantRdbManagerParameter.java
iplass-tools/src/main/resources/mtp-tools-messages.properties
iplass-tools/src/main/resources/mtp-tools-messages_en.properties
iplass-tools/src/main/resources/mtp-tools-messages_ja.properties
iplass-tools/src/main/resources/mtp-tools-service-config.xml

- テーブル存在チェックの大文字・小文字比較不具合修正
- TenantRdbManager にパラメータを追加
- SQLServerのパーティション作成クエリをDBサーバーのOSに依存しない形に修正
- 指定件数ごとにレコードを削除

テナント削除バッチ、大量データの考慮、ストレージスペースデータが一部削除できない

---

iplass-core/src/main/resources/schema/sql/ddl/sqlserver_partition/partition.sql
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/TenantToolService.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/DefaultTenantRdbManager.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/MySQLTenantRdbManager.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/OracleTenantRdbManager.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/PostgreSQLTenantRdbManager.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/SqlServerTenantRdbManager.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/TenantRdbConstants.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/TenantRdbManagerFactory.java
iplass-tools/src/main/java/org/iplass/mtp/impl/tools/tenant/rdb/TenantRdbManagerParameter.java
iplass-tools/src/main/resources/mtp-tools-messages.properties
iplass-tools/src/main/resources/mtp-tools-messages_en.properties
iplass-tools/src/main/resources/mtp-tools-messages_ja.properties
iplass-tools/src/main/resources/mtp-tools-service-config.xml

- テーブル存在チェックの大文字・小文字比較不具合修正
- TenantRdbManager にパラメータを追加
- SQLServerのパーティション作成クエリをDBサーバーのOSに依存しない形に修正
- 指定件数ごとにレコードを削除

テナント削除バッチ、大量データの考慮、ストレージスペースデータが一部削除できない（3.1）

---

iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_en.js
iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_ja.js
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/condition/DateRangePropertySearchCondition.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/condition/NumericRangePropertySearchCondition.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaDateRangePropertyEditor.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/generic/editor/MetaNumericRangePropertyEditor.java
iplass-gem/src/main/java/org/iplass/mtp/view/generic/editor/DateRangePropertyEditor.java
iplass-gem/src/main/java/org/iplass/mtp/view/generic/editor/NumericRangePropertyEditor.java

https://github.com/ISID/iPLAss/issues/1314 対応

GEM、RangePropertyEditorの検索条件で、「<=」「<」、「>=」「>」を指定可能にする

---

iplass-gem/src/main/java/org/iplass/gem/GemConfigService.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/condition/ReferencePropertySearchCondition.java
iplass-gem/src/main/resources/gem-service-config.xml

GEM、詳細検索でReferencePropertyEditorの「表示ラベルとして扱うプロパティ」を考慮する。
ReferencePropertyEditorで「表示ラベルとして扱うプロパティ」として設定された項目を通常検索のテキスト入力による条件指定時、または詳細検索の条件項目として設定します。
後方互換性を保つため、GemConfigServiceにフラグを追加し、挙動を変更できるようにする（デフォルトでは、現状の挙動のまま）。

GEM、詳細検索でReferencePropertyEditorの「表示ラベルとして扱うプロパティ」を考慮する

---

iplass-gem/src/main/java/org/iplass/gem/GemConfigService.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/CsvDownloadSearchContext.java
iplass-gem/src/main/resources/gem-service-config.xml

GEM、検索結果のCSVダウンロードでReferencePropertyEditorの「表示ラベルとして扱うプロパティ」を考慮する。
ReferencePropertyEditorで「表示ラベルとして扱うプロパティ」として設定された項目をCSVダウンロード時にCSV項目として出力する。
後方互換性を保つため、GemConfigServiceにフラグを追加し、挙動を変更できるようにする（デフォルトでは、現状の挙動のまま）。

GEM、検索結果のCSVダウンロードでReferencePropertyEditorの「表示ラベルとして扱うプロパティ」を考慮する

---

iplass-admin/src/main/java/org/iplass/adminconsole/server/base/service/AdminEntityManager.java
iplass-core/src/main/java/org/iplass/mtp/entity/EntityManager.java
iplass-core/src/main/java/org/iplass/mtp/impl/entity/EntityManagerImpl.java
iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/AbstractFulltextSearchService.java
iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/FulltextSearchService.java

全文検索、Entity定義横断でoidのリストのみを返却するメソッドを提供する。
Entity定義横断で全文検索エンジンのみをクエリしてoidのリストを返却する。
複数Entity全部のoidのトータル件数が定数maxRowsを超えないようにスコア降順で上位のものを取得する。

全文検索、Entity定義横断でoidのリストのみを返却するメソッド提供

---

iplass-admin/src/main/java/org/iplass/adminconsole/server/base/io/download/AdminDownloadService.java

AdminConsole、BinaryTemplateの画像がプレビュー表示されない不具合です。
AdminDownloadServiceへdoGetメソッドを追加する。

AdminConsole、BinaryTemplateの画像がプレビュー表示されない

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js

https://github.com/ISID/iPLAss/issues/1345 対応

gem、ReferencePropertyEditorのCheckboxタイプを連動元にした場合に、連動プロパティが制御されない

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp

https://github.com/ISID/iPLAss/issues/1348 対応

gem、ReferencePropertyEditorのCheckboxタイプを連動元にした場合に、連動プロパティが制御されない（3.1）

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Condition.jsp

https://github.com/ISID/iPLAss/issues/1353 対応。
あわせて、参照データをloadしている箇所を、searchEntityで必要最小限に改善。

gem、検索条件でのReferencePropertyEditorの参照コンボにて、上位層しか選択していない場合に、復元されない

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/menu/menu.jsp

gem、Vertical/HorizontalスキンはUrlMenuItemのImage Colorが適用されない

---

iplass-admin/src/main/java/org/iplass/adminconsole/server/base/service/AdminEntityManager.java
iplass-core/src/main/java/org/iplass/mtp/entity/EntityManager.java
iplass-core/src/main/java/org/iplass/mtp/impl/entity/EntityManagerImpl.java
iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/FulltextSearchLuceneService.java
iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/FulltextSearchService.java
iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/lucene/LuceneFulltextSearchService.java

現状、単一のEntity定義に対して、全文検索エンジンのみをクエリしてoidのリストを返却するメソッドは存在するが、 Entity定義横断で全文検索エンジンのみをクエリしてoidのリストを返却するメソッドがないのでそれを追加する。
複数Entity全部のoidのトータル件数が定数maxRowsを超えないようにスコア降順で上位のものを取得する。

全文検索、Entity定義横断でoidのリストのみを返却するメソッド提供（3.1）

---

iplass-gem/src/main/java/org/iplass/gem/command/MetaDataRefs.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/refcombo/GetEditorCommand.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/refcombo/GetReferenceComboSettingCommand.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/refcombo/ReferenceComboCommand.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/refcombo/ReferenceComboData.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/refcombo/SearchParentCommand.java
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Condition.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_RefCombo.jsp
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/flat/design.js
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/horizontal/design.js
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/skin/vertical/design.js
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/webapi.js

https://github.com/ISID/iPLAss/issues/1382 対応
- 多重度1の場合はサーバ側でコンボを生成(refComboSync)
- 検索画面、編集画面の多重度複数の場合は現状通りWebApiで生成(refCombo)
- WebApiでコンボ生成時にEditorを取得していたところをコンボ設定を取得するように変更
　これに伴い、GetEditorCommandを `deprecated` 指定。

gem、NestTableにて参照コンボを動作可能にする

---

iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/AbstractFulltextSearchService.java

全文検索、多重度複数のプロパティで値にnullが含まれると、クロールでエラーが発生する。
オブジェクトNullの分岐を追加し、エラーを解消する。

全文検索、多重度複数のプロパティで値にnullが含まれると、クロールでエラーが発生する

---

iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/FulltextSearchLuceneService.java

全文検索、多重度複数のプロパティで値にnullが含まれると、クロールでエラーが発生する。
オブジェクトNullの分岐を追加し、エラーを解消する。

全文検索、多重度複数のプロパティで値にnullが含まれると、クロールでエラーが発生する（3.1）

---

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java

ReferencePropertyEditorの「表示ラベルとして扱うプロパティ」が未設定の場合はname項目でソートし、設定された場合は、表示ラベルとして扱うプロパティでソートするように修正する。

GEM、大量データ用参照セクション、参照プロパティのソートの挙動修正

---

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java

ReferencePropertyEditorの「表示ラベルとして扱うプロパティ」が未設定の場合はname項目でソートし、設定された場合は、表示ラベルとして扱うプロパティでソートするように修正する。

GEM、大量データ用参照セクション、参照プロパティのソートの挙動修正（3.1）

---

iplass-web/src/main/java/org/iplass/mtp/impl/web/fileupload/FileUploadTikaAdapter.java
iplass-web/src/main/java/org/iplass/mtp/impl/web/fileupload/FileUploadTikaAdapterImpl.java
iplass-web/src/main/java/org/iplass/mtp/impl/web/fileupload/MagicByteCheckApplicationException.java
iplass-web/src/main/java/org/iplass/mtp/impl/web/fileupload/TikaFileTypeDetector.java
iplass-web/src/main/java/org/iplass/mtp/impl/web/fileupload/TikaMagicByteChecker.java
iplass-web/src/main/resources/mtp-web-service-config.xml

- Apache Tika を利用したマジックバイトチェック処理の実装
- TikaFileTypeDetector で利用する Tika インスタンスをマジックバイトチェック処理と共有する
- service-config 設定例を記載

ファイルアップロード、Tikaを利用したマジックバイトチェック機能提供

---

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/entity/property/validation/RangeAttributePane.java

AdminConsole、プロパティのValidator設定はRangeタイプのMin/Maxに負の数や小数を指定できない不具合を修正する。

AdminConsole、プロパティのRangeタイプのValidator設定でMin/Maxに負の数や小数を指定できない

---

iplass-core/src/main/java/org/iplass/mtp/entity/query/condition/Condition.java
iplass-core/src/main/java/org/iplass/mtp/impl/query/prepared/PreparedQueryTemplate.java

Queryテンプレートの実行結果がブランクだった場合にはnullを返すように修正

PreparedQuery#condition、Queryテンプレートの実行結果がブランクだった場合にはnullを返すように

---

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/PartsItem.java

https://github.com/dentsusoken/iPLAss/issues/1446 対応

AdminConsole、gemのTopViewでseparatorで分割している場合に、ダブルクリックで編集ダイアログが２つ開く

---

iplass-admin/src/main/java/org/iplass/adminconsole/client/base/io/upload/AdminUploadActionResponseParser.java
iplass-admin/src/main/java/org/iplass/adminconsole/server/base/io/upload/AdminUploadAction.java

- レスポンスのXMLパース時に結果文字列にルートノードを付与する
- ファイルからbyte配列への変換ロジックを見直し

AdminConsole、ファイルアップロード処理の変更、gwtuploadライブラリの利用停止（バグ修正）

---

iplass-test/build.gradle
iplass-test/libs.gradle
iplass-test/src/demo/groovy/testsample/SampleGroovyTest.groovy
iplass-test/src/demo/java/testsample/SampleJavaTest.java
iplass-test/src/demo/resources/testsample/test-sample-metadata.xml
iplass-test/src/demo/resources/testsample/test-sample-service-config.xml
iplass-test/src/main/java/org/iplass/mtp/test/MTPJUnitTestExtension.java
iplass-test/src/main/java/org/iplass/mtp/test/MTPJUnitTestRule.java
iplass-test/src/main/java/org/iplass/mtp/test/impl/test/MTPTestConfig.java
iplass-test/src/main/java/org/iplass/mtp/test/impl/test/MTPTestConfigComposit.java
iplass-test/src/main/java/org/iplass/mtp/test/impl/test/MTPTestConfigImpl.java
iplass-test/src/main/java/org/iplass/mtp/test/impl/test/MTPTestConfigReader.java
iplass-test/src/main/java/org/iplass/mtp/test/impl/test/MTPTestInvoker.java
iplass-test/src/main/java/org/iplass/mtp/test/impl/test/MTPTestInvokerDecorator.java
iplass-test/src/main/java/org/iplass/mtp/test/impl/test/TestTransactionService.java
sharedlibs.gradle

- JUnit5 バージョンアップ（ 4.13.1 -> 5.10.2 ）。jupiter, vintage を追加
- JUnit4 向けテストサポート機能を JUnit5 向けにマイグレーション
- demo 実装・設定の見直し

テスト、JUnit5系へバージョンアップ

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Condition.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js

表示タイプがLINK、TREE、UNIQUEの場合に作成される参照リンクについて、選択や登録した際にカスタムスタイルを適用するよう修正。
fix #1484

GEM、ReferencePropertyEditorで「選択」や「新規」で動的に追加した参照リンクに対して入力カスタムスタイルを適用する

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Condition.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js

表示タイプがLINK、TREE、UNIQUEの場合に作成される参照リンクについて、選択や登録した際にカスタムスタイルを適用するよう修正。
fix #1507

GEM、ReferencePropertyEditorで「選択」や「新規」で動的に追加した参照リンクに対して入力カスタムスタイルを適用する(4.0)

---

sharedlibs.gradle

ログライブラリバージョンアップ
- org.slf4j:slf4j-api 1.7.36 -> 2.0.13
- org.slf4j:jcl-over-slf4j 1.7.36 -> 2.0.13
- org.slf4j:log4j-over-slf4j 1.7.36 -> 2.0.13
- org.apache.logging.log4j:log4j-to-slf4j 2.19.0 -> 2.23.1
- ch.qos.logback:logback-classic 1.2.13 -> 1.5.6
- net.logstash.logback:logstash-logback-encoder 7.0.1 -> 7.4
- 画面動作確認（ce, ee）
特になし

ログ関連ライブラリ、バージョンアップ（4.0）

---

iplass-core/src/main/java/org/iplass/mtp/impl/properties/extend/BinaryType.java
iplass-gem/src/main/java/org/iplass/gem/command/calendar/GetCalendarCommand.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/condition/BooleanPropertySearchCondition.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/condition/DatePropertySearchCondition.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/condition/PropertySearchCondition.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/condition/SelectPropertySearchCondition.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/condition/TimePropertySearchCondition.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/condition/TimestampPropertySearchCondition.java
sharedlibs.gradle

- commons-text 1.2 -> 1.12.0
- 非推奨クラスの変更 ( org.apache.commons.text.StrTokenizer -> org.apache.commons.text.StringTokenizer )
- 画面動作確認
- カレンダー、いずれかと等しい条件指定
- 汎用検索、いずれかと等しい詳細条件指定（文字列）
- 汎用エンティティ、バイナリデータ保存、表示
特になし

commons-text、バージョンアップ（4.0）

---

iplass-admin/src/main/java/org/iplass/adminconsole/server/metadata/rpc/message/MessageItemCsvReader.java
iplass-admin/src/main/java/org/iplass/adminconsole/server/tools/rpc/langexplorer/LangCsvReader.java
iplass-tools-batch/src/main/java/org/iplass/mtp/tools/batch/entity/EQLExecutor.java
iplass-web/src/main/java/org/iplass/mtp/impl/web/RangeHeader.java
sharedlibs.gradle

- commons-io 2.15.1 -> 2.16.1
- BOMInputStream コンストラクタから builder に変更
- CloseShieldOutputStream コンストラクタから wrap に変更
- BoundedInputStream コンストラクタから builder に変更
- 
- 汎用エンティティ動作確認（登録、変更、表示、削除）
- AdminConsole Lang CSV アップロード（BOM 有無）
- AdminConsoel Message CSV アップロード（BOM 有無）
- Batch EQLExecutor 実行確認（結果表示）
- RangeHeader 確認（StaticResource のGETで確認）
特になし

commons-io、バージョンアップ（4.0）

---

iplass-gem/src/main/java/org/iplass/gem/command/auth/UserPasswordRegistrationInterrupter.java
iplass-gem/src/main/java/org/iplass/mtp/view/generic/RegistrationInterrupter.java

既存のインターフェースはDeprecatedとして、新規インターフェースから呼び出す。
UserPasswordRegistrationInterrupterについては、カスタマイズを考慮し、beforeRegist のまま残す。
close #1538

GEM、RegistrationInterrupterのインターフェース変更（旧インターフェースをDeprecatedとして残す）

---

iplass-web/src/main/java/org/iplass/mtp/csv/CsvUploadInterrupter.java

既存のインターフェースはDeprecatedとして、新規インターフェースから呼び出す。
close #1539

GEM、SearchFormCsvUploadInterrupterのインターフェース変更（旧インターフェースをDeprecatedとして残す）

---

sharedlibs.gradle

- jakarta ee 10 対応時の jersey バージョンアップタイミングで不足していた 'org.glassfish.jersey.media:jersey-media-jaxb' を追加
- WebAPI の実行確認
- 特になし

JakartaEE10/Tomcat10.1、Java 21対応 - webapi 実行エラー対応

---

iplass-core/libs.gradle
iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/lucene/JapaneseAnalyzerSetting.java
iplass-core/src/main/java/org/iplass/mtp/impl/fulltextsearch/lucene/LuceneFulltextSearchService.java
sharedlibs.gradle

- lucene-queryparser 8.11.2 -> 9.11.1
- lucene-queryparser の exclude 指定を除去
- lucene-analyzers-kuromoji 8.11.2 -> lucene-analysis-kuromoji 9.11.1
- lucene-backward-codecs 8.11.2 -> 9.11.1
- lucene-highlighter を削除
- lucene-analyzers-smartcn (lucene-analysis-smartcn) を削除
- MMapDirectory.DEFAULT_MAX_CHUNK_SIZE のデータ型 long に変更に伴うコード修正
- deprecated メソッド StopwordAnalyzerBase.loadStopwordSet ⇒ WordlistLoader.getWordSet へ変更
- deprecated メソッド IndexSearcher.doc ⇒ IndexSearcher.storedFields(), StoredFields.document へ変更
- AdminConsoleよりクロール実施（index バージョン 8, 9 両方）
- インデックスより検索（index バージョン 8, 9 両方）
- バッチ経由のクロール
- 修正箇所確認（stopwords, stoptags の読み込み）
特になし

lucene、バージョンアップ（4.0）

---

iplass-admin/src/main/java/org/iplass/adminconsole/server/base/io/upload/AdminUploadAction.java
iplass-gem/src/main/java/org/iplass/gem/GemConfigService.java
iplass-web/src/main/java/org/iplass/mtp/impl/webapi/WebApiService.java
sharedlibs.gradle

- org.apache.poi:poi 5.2.3 -> 5.3.0
- org.apache.poi:poi-scratchpad 5.2.3 -> 5.3.0
- org.apache.poi:poi-ooxml 5.2.3 -> 5.3.0
- org.apache.poi.util の参照を変更
- JasperReport レポート出力テスト
- JXLS レポート出力表示テスト
- POI レポート出力テスト
- web 以外のプロジェクトの org.apache.poi.util 参照を、適切なパッケージに変更

POI、バージョンアップ（4.0）

---

iplass-web/src/main/java/org/iplass/mtp/impl/webapi/jackson/EntityDeserializer.java
iplass-web/src/main/java/org/iplass/mtp/impl/webapi/jackson/WebApiParameterDeserializer.java
sharedlibs.gradle

- com.fasterxml.jackson:jackson-bom 2.15.2 -> 2.17.2
- フレームワークメソッド削除によるコンパイルエラー解消
- 動作確認後のコメントを追記
- 汎用エンティティ操作（新規登録、更新、参照、削除）
- WebApiParameterMap Parameter タイプの WebAPI 動作検証（正常系、エラー系の確認）
- Entity Parameter タイプの WebAPI 動作確認（正常系、エラー系の確認）
- ObjectMapper#configure で設定するパラメータの deprecated は最後に作業する

jackson、バージョンアップ（4.0）

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/ckeditorResource.inc.jsp
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/plugin/ckeditor/mtpconfig.js

CKEditorのデフォルト設定で「versionCheck: false」を指定することで警告メッセージを抑制する。
close #1554

GEM: CKEditor利用時に警告メッセージが表示されるのを抑制する

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/string/StringPropertyEditor_Edit.jsp

多重度複数のLongTextプロパティなどに対して、LongTextPropertyEditorの RICHTEXTタイプを指定している場合に、
編集画面で「追加」ボタンで追加した結果表示されるEditorに対しても RickText Editor Option を適用する。
close #1563

GEM、多重度複数のプロパティに対してRichTextEditorを使用している場合に、追加ボタンで表示されるEditorにOptionが適用されない

---

build.gradle

- test プロジェクトの構成上、doc 出力時の classpath に test プロジェクトのsrcDir を含める必要があるため追加
- javadocI18n タスク実行
特になし

テスト、JUnit5系へバージョンアップ javadoc出力設定修正

---

iplass-web/libs.gradle
sharedlibs.gradle

- net.sf.jasperreports:jasperreports 6.20.6 -> 6.21.3
- com.github.librepdf:openpdf 1.3.33 -> 2.0.2
- 帳票テンプレート（JasperReports）を利用した帳票出力の実行
特になし

JasperReports、バージョンアップ（4.0）

---

iplass-core/libs.gradle
iplass-web/libs.gradle
iplass-web/src/main/java/org/iplass/mtp/impl/web/fileupload/TikaFileTypeDetector.java
sharedlibs.gradle

- org.apache.tika:tika-core 1.28.5 -> 2.9.2
- org.apache.tika:tika-parsers 1.28.5 は以下のモジュールに変更
-> org.apache.tika:tika-parser-html-module 2.9.2
-> org.apache.tika:tika-parser-xml-module 2.9.2
-> org.apache.tika:tika-parser-microsoft-module 2.9.2
-> org.apache.tika:tika-parser-pdf-module 2.9.2
-> org.apache.tika:tika-parser-zip-commons 2.9.2
- parser 用に個別に追加していた依存関係の整理
- TikaFileTypeDetector で FileUploadTikaAdapter の設定を必須とする
- 汎用エンティティ操作（新規登録、更新、表示、削除）
- 全文検索バイナリファイルクロール実行、検索実行
- Tika を利用したファイルアップロード実施
- parser については service-config で解析可能なファイルタイプを確認し必要最低限の設定としてあります。

Tika、バージョンアップ（4.0）

---

sharedlibs.gradle

Jakarta EE 10, Tomcat 10.1 対応を実施した際に更新したライブラリバージョンの再チェックを実施する。
- org.apache.tomcat:tomcat-jasper 10.1.20 -> 10.1.26
- org.glassfish.jersey:jersey-bom 3.1.5 -> 3.1.7
- org.bouncycastle:bcjmail-jdk18on 1.78 -> 1.78.1
- mdc 汎用エンティティ操作（新規登録、更新、参照、削除）
- WebAPI 操作
特になし

JakartaEE10/Tomcat10.1、Java 21対応 - ライブラリ最新化

---

iplass-gem/libs.gradle
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/binary/pdfviewer.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/calendarResource.inc.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/coreResource.inc.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/datepickerResource.inc.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/mediaelementResource.inc.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/viewerjsResource.inc.jsp
sharedlibs.gradle

- org.webjars:jquery 3.5.1 -> 3.7.1
- org.webjars.bowergithub.jquery:jquery-ui 1.13.2 -> org.webjars.npm:jquery-ui 1.13.3
- org.webjars:pdf-js 4.2.67 -> 4.4.168
- org.webjars:momentjs 2.29.4 -> org.webjars.npm:moment 2.30.1
- org.webjars.npm:viewerjs 1.9.0 -> 1.11.1
- org.webjars.bower:blueimp-file-upload 10.30.1 -> org.webjars.npm:blueimp-file-upload 10.32.0
- org.webjars.bower:mediaelement 4.2.5 -> org.webjars.npm:mediaelement 4.2.17
- org.webjars.bower:fullcalendar 3.10.2 -> org.webjars.npm:fullcalendar 3.10.5
- gemでEntityデータの検索、新規、編集、削除
- カレンダーにてデータの表示、登録、編集
- Entityデータ登録時にbinaryファイルのアップロードと登録後binaryファイルの表示
- gem/binary/pdfviewer経由でpdfの表示
特になし

jQuery、その他のWebJars管理のJavaScriptライブラリバージョンアップ

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/string/StringPropertyEditor_View.jsp

検索結果を出力する際に、 サーバ側でjspを経由して結果を処理しているが、
この場合は `staticContentPath` が未設定のためJavaScriptのロードエラーが発生。
ただし、そもそも `RICHTEXT` は詳細画面、編集画面のみに対応しているため、
CKEditorのリソースをロードしないように対応。
fixes #1598

GEM、検索結果でRICHTEXTを利用するとエラーになる

---

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/SearchContextBase.java

ソート時に大量データ参照セクション、検索結果の表示プロパティまでしかソート対象としてチェックしていなかったのを、ReferencePropertyEditorの表示プロパティまでチェックするよう修正
close #1588

大量データ参照セクション、検索結果で参照プロパティのネスト項目ソート時の動きを修正

---

iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/GetMassReferencesCommand.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/SearchContextBase.java

ソート時に大量データ参照セクション、検索結果の表示プロパティまでしかソート対象としてチェックしていなかったのを、ReferencePropertyEditorの表示プロパティまでチェックするよう修正
close https://github.com/dentsusoken/iPLAss/issues/1595

大量データ参照セクション、検索結果で参照プロパティのネスト項目ソート時の動きを修正（4.0）

---

build.gradle
sharedlibs.gradle

- JavaDoc 生成時に classpath を設定しないと出力できない問題の対応
- jackson-bom の依存関係を jakartaImplRest に追加、jeeruntime4tomcat から削除
- Javadoc 生成実行（ `.\gradlew.bat javadocI18n` )
特になし

JakartaEE10/Tomcat10.1、Java 21対応 - Javadoc 生成できない

---

iplass-web/src/main/java/org/iplass/mtp/impl/csv/CsvUploadService.java

同じOIDに対して無効データのみのEntityデータに対して、CSVアップロードを利用して、「新しいバージョンとして更新」しようとしても「新規追加」として、別のOIDデータとして登録されてしまう。
登録済の状態を判定する際に、無効データも含めたチェックを行う。
fixes #1625
バージョン管理Entityに対して、
1. CSVでバージョンが指定されている場合
　全バージョン含めて指定された oid 、version のデータが存在するか検索
1.1. 指定バージョンが存在する場合は対象バージョンを更新 (**`UPDATE_SPECIFIC`**)
1.2. 指定バージョンが存在しない場合は、oid で登録状態をチェック
　有効データに指定された oid のデータが存在するか検索
1.2.1. 有効データに oid データが存在する場合は、新しいバージョンとして追加 (**`UPDATE_NEW`**)
　新しいバージョンの元となるバージョンは有効データとする（version=nullで更新）
1.2.2. 有効データに oid データが存在しない場合は、全バージョン含めて oid の登録状態をチェック
　全バージョン含めて指定された oid のデータが存在するか検索
1.2.2.1. 全バージョンに oid データが存在する場合は、新しいバージョンとして追加 (**`UPDATE_NEW`**)
　新しいバージョンの元となるバージョンは登録済 version のMAX値データとする
1.2.2.2 全バージョンに oid データが存在しない場合は、追加する (**`INSERT`**)
2. CSVでバージョンが指定されていない場合
　有効データに指定された oid のデータが存在するか検索。1.2と同様のチェックを行う。

gem、CSVアップロード、バージョン管理されていて無効データしか存在しない場合に、NEW_VERSIONとして更新できるようにする（3.1）

---

iplass-web/src/main/java/org/iplass/mtp/impl/csv/CsvUploadService.java
iplass-web/src/main/resources/mtp-web-messages.properties
iplass-web/src/main/resources/mtp-web-messages_en.properties
iplass-web/src/main/resources/mtp-web-messages_ja.properties
iplass-web/src/main/resources/mtp-web-messages_th.properties
iplass-web/src/main/resources/mtp-web-messages_zh.properties
iplass-web/src/main/resources/mtp-web-messages_zh_HK.properties
iplass-web/src/main/resources/mtp-web-messages_zh_TW.properties

同じOIDに対して無効データのみのEntityデータに対して、CSVアップロードを利用して、「新しいバージョンとして更新」しようとしても「新規追加」として、別のOIDデータとして登録されてしまう。
登録済の状態を判定する際に、無効データも含めたチェックを行う。
fixes #1623
バージョン管理Entityに対して、
1. CSVでバージョンが指定されている場合
　全バージョン含めて指定された oid 、version のデータが存在するか検索
1.1. 指定バージョンが存在する場合は対象バージョンを更新 (**`UPDATE_SPECIFIC`**)
1.2. 指定バージョンが存在しない場合は、oid で登録状態をチェック
　有効データに指定された oid のデータが存在するか検索
1.2.1. 有効データに oid データが存在する場合は、新しいバージョンとして追加 (**`UPDATE_NEW`**)
　新しいバージョンの元となるバージョンは有効データとする（version=nullで更新）
1.2.2. 有効データに oid データが存在しない場合は、全バージョン含めて oid の登録状態をチェック
　全バージョン含めて指定された oid のデータが存在するか検索
1.2.2.1. 全バージョンに oid データが存在する場合は、新しいバージョンとして追加 (**`UPDATE_NEW`**)
　新しいバージョンの元となるバージョンは登録済 version のMAX値データとする
1.2.2.2 全バージョンに oid データが存在しない場合は、追加する (**`INSERT`**)
2. CSVでバージョンが指定されていない場合
　有効データに指定された oid のデータが存在するか検索。1.2と同様のチェックを行う。

gem、CSVアップロード、バージョン管理されていて無効データしか存在しない場合に、NEW_VERSIONとして更新できるようにする

---

iplass-web/src/main/java/org/iplass/mtp/impl/csv/CsvUploadService.java
iplass-web/src/main/resources/mtp-web-messages_en.properties
iplass-web/src/main/resources/mtp-web-messages_ja.properties
iplass-web/src/main/resources/mtp-web-messages_th.properties
iplass-web/src/main/resources/mtp-web-messages_zh.properties
iplass-web/src/main/resources/mtp-web-messages_zh_TW.properties

同じOIDに対して無効データのみのEntityデータに対して、CSVアップロードを利用して、「新しいバージョンとして更新」しようとしても「新規追加」として、別のOIDデータとして登録されてしまう。
登録済の状態を判定する際に、無効データも含めたチェックを行う。
fixes #1624
バージョン管理Entityに対して、
1. CSVでバージョンが指定されている場合
　全バージョン含めて指定された oid 、version のデータが存在するか検索
1.1. 指定バージョンが存在する場合は対象バージョンを更新 (**`UPDATE_SPECIFIC`**)
1.2. 指定バージョンが存在しない場合は、oid で登録状態をチェック
　有効データに指定された oid のデータが存在するか検索
1.2.1. 有効データに oid データが存在する場合は、新しいバージョンとして追加 (**`UPDATE_NEW`**)
　新しいバージョンの元となるバージョンは有効データとする（version=nullで更新）
1.2.2. 有効データに oid データが存在しない場合は、全バージョン含めて oid の登録状態をチェック
　全バージョン含めて指定された oid のデータが存在するか検索
1.2.2.1. 全バージョンに oid データが存在する場合は、新しいバージョンとして追加 (**`UPDATE_NEW`**)
　新しいバージョンの元となるバージョンは登録済 version のMAX値データとする
1.2.2.2 全バージョンに oid データが存在しない場合は、追加する (**`INSERT`**)
2. CSVでバージョンが指定されていない場合
　有効データに指定された oid のデータが存在するか検索。1.2と同様のチェックを行う。

無効データのみの場合のUPDATE_NEW対応

---

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/top/item/InformationItem.java
iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_en.js
iplass-admin/src/main/resources/org/iplass/adminconsole/public/locale/locale_ja.js
iplass-gem/src/main/java/org/iplass/gem/command/information/InformationListCommand.java
iplass-gem/src/main/java/org/iplass/gem/command/information/InformationViewCommand.java
iplass-gem/src/main/java/org/iplass/mtp/impl/view/top/parts/MetaInformationParts.java
iplass-gem/src/main/java/org/iplass/mtp/view/top/parts/InformationParts.java

- TopView用お知らせパーツに多言語対応フラグを追加
- お知らせ関連Commandの検索処理に多言語データの考慮オプションを設定
closes #1616 
以下を確認した。
- 変更前のバージョンにおけるTopViewのメタデータを、変更後のバージョンの環境で読み込めること
多言語対応フラグがOFFの場合：
- Entitiyの多言語対応状態にかかわらず、多言語を考慮しないデータが検索される
多言語対応フラグがONの場合：
- Entityが多言語対応されていれば、多言語を考慮したデータが検索される
- Entityが多言語対応されていなければ、多言語を考慮しないデータが検索される

TopView用お知らせパーツ: 多言語対応データを検索可能にする

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/string/richtext/ckeditor/CKEditor_Add.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/string/richtext/ckeditor/CKEditor_Edit.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/string/richtext/ckeditor/CKEditor_NestTable.jsp

`RickText Editor Option` が指定された場合も、 オプションとしては `allowedContent` を指定した上で、`RickText Editor Option` で上書きすることを可能にする。
closes #1643

編集画面のCKEditorオプション制御の変更

---

iplass-gem/src/main/java/org/iplass/gem/command/binary/UploadCommand.java
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js

- UploadCommandにて、RequestContextに対する処理をtry、catchで囲む。
　RuntimeException発生時は、レスポンスとしてエラーメッセージを返す。
　ApplicationException発生時はそのメッセージを、それ以外は固定メッセージを設定する。
- JavaScript側にて、サーバーエラー発生時(status500など)の制御を行う。
　現状、制御できていないため、ローディング表示が消えていなかった。
closes #1645

ファイルアップロード時のエラー制御改善

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/layout/resource/locale.jsp

選択言語がen以外の場合、enのgem-locale.jsをデフォルトとして適用する。
closes #1638

言語がen以外の場合、enのgem-locale.jsをデフォルトとして適用

---

iplass-gem/src/main/java/org/iplass/gem/command/generic/search/SearchListCommand.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/SearchListPartsCommandBase.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/SearchNameListCommand.java
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/search/list.jsp
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/functions.js
iplass-gem/src/main/resources/META-INF/resources/scripts/gem/webapi.js

closes #1618 
1. パーツ関連Commandでのcountクエリ実行処理を削除
2. パーツにおける次ページの存在判定処理を、countクエリの結果に依存せず同等の動作となるよう変更
Commandでは、 `[Admin Consoleでの表示件数の設定値] + 1` 行を検索させる。
画面側では、検索結果の行数が `[Admin Consoleでの表示件数の設定値]` より大きい場合に「次ページが存在する」と判定させる。
その後、検索結果の行数が  `[Admin Consoleでの表示件数の設定値]` と一致するように、検索結果リストをsliceさせる。
- TopViewのMain AreaとWidget両方で確認
- Admin Consoleで表示件数が **設定されている** 場合に、パーツのページング動作が変更前と同様であること
- Admin Consoleで表示件数が **設定されていない** 場合に、パーツのページング動作が変更前と同様であること
- Entityの検索画面で確認
- Admin Consoleで表示件数が **設定されている** 場合に、画面のページング動作が変更前と同様であること
- Admin Consoleで表示件数が **設定されていない** 場合に、画面のページング動作が変更前と同様であること

GEM: TopViewの検索結果一覧パーツでcountクエリを実行しないようにする

---

iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/data/logexplorer/LogFileDS.java
iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/logexplorer/LogExplorerFileListPane.java
iplass-admin/src/main/java/org/iplass/adminconsole/server/base/service/AdminConsoleService.java
iplass-admin/src/main/java/org/iplass/adminconsole/server/tools/rpc/logexplorer/LogExplorerServiceImpl.java
iplass-admin/src/main/java/org/iplass/adminconsole/shared/tools/dto/logexplorer/LogFileCondition.java
iplass-admin/src/main/java/org/iplass/adminconsole/shared/tools/rpc/logexplorer/LogExplorerService.java
iplass-admin/src/main/java/org/iplass/adminconsole/shared/tools/rpc/logexplorer/LogExplorerServiceAsync.java

AdminConsoleのLogExplorerにて、対象のログファイルのPathを正規表現で絞り込めるようにする。
- PathとLast Modified列の上部にFilter入力欄を表示。
- 正規表現にてファイルを絞り込む（Matcher#find()）。
closes #1662

ログファイルのフィルター機能実装

---

sharedlibs.gradle

- logback-classic 1.5.6 -> 1.5.16 （2025-01-17 時点の最新版）
- アプリケーション動作確認（ログ出力確認）
特になし

logbackバージョンアップ

---

iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/data/logexplorer/LogFileDS.java
iplass-admin/src/main/java/org/iplass/adminconsole/client/tools/ui/logexplorer/LogExplorerFileListPane.java
iplass-admin/src/main/java/org/iplass/adminconsole/server/tools/rpc/logexplorer/LogExplorerServiceImpl.java
iplass-admin/src/main/java/org/iplass/adminconsole/shared/tools/dto/logexplorer/LogFileCondition.java

LogExplorerにて、画面上でログファイルの表示件数のLimitを指定可能にする。
デフォルトは100とする。
closes #1673
Limitについて、 service-config で `logHome` として指定されたフォルダを、複数ある場合は先頭から順番に検索し、
各フォルダに対して、 `File#listFiles()` により取得される順番でLimitまでファイルを取得する。
画面上でのファイル名などでのソート指定（降順など）は、Limitまで取得されたデータに適用される。
フォルダをソートした状態に対して、Limitをチェックするわけではない。

LogExplorerのLimit対応

---

iplass-core/src/main/java/org/iplass/mtp/util/StringUtil.java

iplass-coreの `StringUtil` に、文字列をJSON用にエスケープ・アンエスケープする機能を追加する。
closes #1689 
以下を含む文字列をエスケープできることを確認した。
- `\"`
- `\\`
- `/`
- `\b`
- `\f`
- `\n`
- `\r`
- `\t`

文字列をJSON用にエスケープ・アンエスケープする機能を追加

---

iplass-gem/src/main/java/org/iplass/gem/GemConfigService.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/BulkCommandContext.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/MultiBulkCommandContext.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/RegistrationCommandContext.java
iplass-gem/src/main/resources/gem-service-config.xml

- GemConfigServiceに `mustLoadWithReference` を追加
　falseの場合、更新時に参照先の再Loadを行わない。保持するプロパティ値は oid と version のみ。
　デフォルトは既存処理に合わせ true とする。
- 上記がtrueの場合は、既存の処理同様、GemConfigServiceの `loadWithReference` の設定により、LoadOptionを制御する
　ただしこの際も、 `EntityManager#batchLoad` により、一括でLoadする。
closes #1700
- Validationエラーなどで編集画面が再表示される際に、表示プロパティが指定されていても、oid version で再検索して表示しているため、正しく表示されている
- 既存の処理に合わせて、デフォルト値は true とする。本来であれば、 false のほうがパフォーマンスはいい。

Entity更新時の参照先のロード処理のパフォーマンス改善

---

iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/BulkCommandContext.java

一括更新系のCommandがリクエスト情報から更新対象を取得する際に、リクエストにおける更新対象の順序が維持されるよう修正する。
fixes: #1706 
動作確認用に、 `BulkOperationInterrupter` を実装するクラスを作成し、 `beforeOperation()` で `BulkOperationContext` 内の更新対象Entityリストをソートするよう実装した。
上記クラスをEntityのSearchViewに設定し、以下を確認した。
- 「検索条件を元に全て一括更新」により一括更新した際に、 `BulkUpdateListCommand` で取得された更新対象が  `BulkUpdateAllCommand` でのInterrupterによるソート順通りになっていること
- 「選択された行を一括更新」による一括更新をこれまで通り実行できること

GEM: 一括更新Commandにおける対象の取得時に、対象のソート順が維持されるよう修正

---

iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/BulkCommandContext.java

fixes #1708 
動作確認用に、 BulkOperationInterrupter を実装するクラスを作成し、 beforeOperation() で BulkOperationContext 内の更新対象Entityリストをソートするよう実装した。
上記クラスをEntityのSearchViewに設定し、以下を確認した。
- 「検索条件を元に全て一括更新」により一括更新した際に、 BulkUpdateListCommand で取得された更新対象が BulkUpdateAllCommand でのInterrupterによるソート順通りになっていること
- 「選択された行を一括更新」による一括更新をこれまで通り実行できること

GEM: 一括更新Commandにおける対象の取得時に、対象のソート順が維持されるよう修正 （3.2）

---

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/webapi/RestJsonParamPane.java
iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/webapi/RestXmlParamPane.java

- RestJson, RestXml の acceptableContentType の null チェック追加
- RestJson, RestXml が設定されている WebAPI 画面再表示時に、画面設定内容が表示されることを確認
- RestJson, RestXml が設定されている WebAPI 画面再表示時に、ブラウザの開発者ツールで JS エラーが発生しないことを確認
- 不具合原因は null 配列に対しての文字連結操作（ `String.join(String, String[])` )を実施していたため

Web: WebAPIでリクエストのAcceptable Content Typeが未設定の場合、WebAPI定義情報が画面で正しく表示されないことがある

---

iplass-gem/src/main/java/org/iplass/gem/command/generic/search/NormalSearchContext.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/condition/ExpressionPropertySearchCondition.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/search/condition/StringPropertySearchCondition.java

1. NormalSearchContextにelse分岐を追加し、Boolean型およびAutoNumber型の検索条件の処理を正常に動くできます。
2. String型の検索条件ParamsはすべてString[]として統一し、1番目は単独の検索値、2番目と3番目は範囲検索のfromとtoを表します。
3. Expression型では、String型の検索条件がString[]として処理されるロジックを追加しました。
4. Expression型では、Boolean型の検索条件をString型に変換する処理を修正し、BooleanPropertySearchConditionによる処理を容易にしました。
fixes [#1731](https://github.com/dentsusoken/iPLAss/issues/1731)
■String型
■Boolean型
■AutoNumber型
■Expression型
■Reference型

GEM：ExpressionPropertyを利用している場合，ClassCastException発生します ＆ 部分検索条件にただしくない

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/string/StringPropertyEditor_Edit.jsp
iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/flat/module.css
iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/horizontal/module.css
iplass-gem/src/main/resources/META-INF/resources/styles/gem/skin/vertical/module.css
iplass-gem/src/main/sass/basedesign/module/common/_input.scss
iplass-gem/src/main/sass/flat/module/common/_input.scss

backport of #1679 
closes #1736 
Entityの新規作成画面と編集画面に、テキストエリアコンポーネントの右下をドラッグし、幅が親コンポーネントの範囲を超えません
※単件と複数件、両方も確認した
※全スキンで動作確認追加、問題なし

GEM: テキストエリアを画面幅以上に拡大できてしまう（3.2）

---

iplass-core/src/main/java/org/iplass/mtp/impl/warmup/MetaDataWarmupTask.java
iplass-core/src/main/java/org/iplass/mtp/impl/warmup/WarmupContext.java
iplass-core/src/main/java/org/iplass/mtp/impl/warmup/WarmupService.java
iplass-core/src/main/java/org/iplass/mtp/impl/warmup/WarmupStatus.java
iplass-core/src/main/java/org/iplass/mtp/impl/warmup/WarmupTask.java
iplass-core/src/main/resources/mtp-core-service-config.xml
iplass-gem/src/main/resources/gem-service-config.xml
iplass-web/src/main/java/org/iplass/mtp/impl/web/WarmupStatusServlet.java
iplass-web/src/main/java/org/iplass/mtp/impl/web/warmup/WebWarmupContextConstant.java
iplass-web/src/main/resources/META-INF/web-fragment.xml
iplass-web/src/main/resources/mtp-web-service-config.xml

- ウェブアプリ起動時ウォームアップおよび状態取得するサーブレットを追加
- ウォームアップサービスを追加
- メタデータウォームアップタスクを追加
- core, gem でデフォルトのメタデータウォームアップ設定を追加
- アプリケーション起動し、ウォームアップ機能が動作することの確認
- ステータスサーブレットの確認
- #1730 のバックポートです

メタデータのプリフェッチ機能（3.2）

---

iplass-gem/src/main/java/org/iplass/gem/command/Constants.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailViewCommand.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/UpdateCommand.java
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/edit.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/detail/view.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/element/section/VersionSection.jsp

- バージョン指定して詳細画面に遷移する際に、リクエスト情報に `versionSpecified = true` を設定
- この詳細画面から編集画面に遷移する際も、同様に `versionSpecified = true` を設定
これにより更新時に `RegistrationCommandBase#update()` で `targetVersion` に `TargetVersion.SPECIFIC` が設定され、特定バージョンのデータを更新できるようになる。
fixes #1688 
* Improved code formatting for better readability in `DetailViewCommand.java` and `UpdateCommand.java`. [[1]](diffhunk://#diff-7df0302a506a72f728a16b6a445d88416883606f00b351856370d226b540a681L67-R68) [[2]](diffhunk://#diff-29b77823b7d58d4aaff8609fd7b33fb3cf2c53d707d30574481d2b48ab50822bL56-R57)
任意のバージョン管理されたEntityについて、複数バージョンのデータを作成する。
その後、EntityViewの検索画面でEntityデータを検索し、上記データの詳細画面を開く。
以下、この詳細画面を `状態A` とする。
1. 状態Aの「別バージョンを参照」から特定バージョンの詳細画面 → 編集画面へと遷移し、データを更新できること
2. 状態Aから現バージョンの編集画面を開き、キャンセルボタンを押して詳細画面に戻る。その後「1」を実施し、データを更新できること
3. …

GEM: 詳細画面から特定バージョンに遷移した場合でもEntityを更新できるよう修正

---

iplass-admin/src/main/java/org/iplass/adminconsole/client/metadata/ui/tenant/BaseTenantPropertyEditDialog.java

Closes #1756
AdminConsoleのカラースキームとダークカラースキームの設定ダイアログの高さを項目数に合わせて調節する。

AdminConsole: カラー設定ダイアログの高さが動的に設定されるようにする

---

iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/BulkCommandContext.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Table.jsp

fixes #1745
- 登録（編集）画面内に複数のネストテーブルがある場合でも表示順の変更が正常に動作するように修正
- 一括更新（単項目）時に更新項目にネストテーブル設定したリファレンスプロパティを選択して一括更新したときのエラーを修正

GEM: 表示順プロパティを設定したNestTableが複数存在する場合に、1つ目のNestTableの表示順で他のNestTableがソートされてしまう

---

iplass-gem/src/main/java/org/iplass/gem/command/generic/bulk/BulkCommandContext.java
iplass-gem/src/main/java/org/iplass/gem/command/generic/detail/DetailCommandContext.java
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Table.jsp

fixes #1746
- 登録（編集）画面内に複数のネストテーブルがある場合でも表示順の変更が正常に動作するように修正
- 一括更新（単項目）時に更新項目にネストテーブル設定したリファレンスプロパティを選択して一括更新したときのエラーを修正

GEM: 表示順プロパティを設定したNestTableが複数存在する場合に、1つ目のNestTableの表示順で他のNestTableがソートされてしまう（3.2）

---

iplass-admin/src/main/java/org/iplass/adminconsole/client/base/ui/widget/ScriptEditorDialogConstants.java

closes #1791 
以下を確認した。
- 定数削除によるコンパイルエラーが発生しないこと

不要な定数を削除（#1791）

---

iplass-gem/src/main/resources/META-INF/resources/scripts/gem/common.js

fixes #1786
GEM:詳細画面からリファレンス編集時のCallback関数をカスタマイズできるようにする

GEM:詳細画面からリファレンス編集時のCallback関数をカスタマイズできるようにする

---

iplass-admin/src/main/java/org/iplass/adminconsole/server/base/io/upload/CommonsFileuploadMultipartRequestParameter.java
sharedlibs.gradle

- org.apache.commons:commons-fileupload2-jakarta-servlet6 2.0.0-M2 -> 2.0.0-M4
-  (推移依存ライブラリ）commons-io:commons-io 2.15.1 -> 2.19.0
- commons-fileupload バージョンアップによるコンパイルエラー対応
- エンティティビューで参照・登録・更新・削除の確認
- ファイルアップロード操作の確認（gem・AdminConsole）

Commons FileUpload 2.0.0-M4 バージョンアップ

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/bulk/bulkEdit.jsp

backport of #1811 
closes #1813 
4.0と同じケースを使用してテストを実施しました
※ケースが完全に一致しているため、エビデンスは作成しておりません。

GEM: 多重度が1以上のプロパティを未入力のまま一括更新すると、画面の表示が崩れる（3.2）

---

iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/reference/ReferencePropertyEditor_Edit.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/select/SelectPropertyEditor_Edit.jsp
iplass-gem/src/main/resources/META-INF/resources/jsp/gem/generic/editor/string/StringPropertyEditor_Edit.jsp
iplass-gem/src/main/resources/mtp-gem-messages.properties
iplass-gem/src/main/resources/mtp-gem-messages_en.properties
iplass-gem/src/main/resources/mtp-gem-messages_ja.properties
iplass-gem/src/main/resources/mtp-gem-messages_th.properties
iplass-gem/src/main/resources/mtp-gem-messages_zh.properties
iplass-gem/src/main/resources/mtp-gem-messages_zh_HK.properties
iplass-gem/src/main/resources/mtp-gem-messages_zh_TW.properties

多重度が1以上・タイプが「CHECKBOX」または「SELECT」の場合、エディタに選択件数の制限を追加します。
選択数が多重度以上の場合、エラーメッセージを表示します
closed #1817

GEM:多重度が「1」以上 の場合、多重度以上の項目を選択した場合に自動的にトリムされてしまうことを改善
